using CinemaApp.DataAccess.Data;
using CinemaApp.Models.DomainModels;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace CinemaApp.DataAccess.Seed
{
    public class AddDbInitializer
	{
		public static void Seed(IApplicationBuilder applicationBuilder)
		{
			using (var serviceScope = applicationBuilder.ApplicationServices.CreateScope())
			{
				var db = serviceScope.ServiceProvider.GetService<ApplicationDbContext>();
				
				db.Database.EnsureCreated();

				if (!db.Genres.Any())
				{
					db.Genres.AddRange(new List<Genre>
					{
						new Genre { Name = "Comedy" },
						new Genre { Name = "Thriller" },
						new Genre { Name = "Romance" },
						new Genre { Name = "Sci-Fi" },
						new Genre { Name = "Drama" },
						new Genre { Name = "Action" },
						new Genre { Name = "Crime" },
						new Genre { Name = "Animation" },
						new Genre { Name = "War" },
						new Genre { Name = "Music" }
					});
					db.SaveChanges();
				}

				if (!db.Movies.Any())
				{
					db.Movies.AddRange(new List<Movie>
					{
						new Movie
						{
							Title = "Shrek",
							Description = "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, " +
							"who must go on a quest and rescue a princess for the lord in order to get his land back.",
							Director = "Andrev Adamson, Vicky Jenson",
							MainActor = "Mike Meyers, Eddie Murphy, Cameron Diaz",
							ReleaseDate = new DateTime(2001,1,1),
							Duration = 90,
							TicketPrice = 14
						},
						new Movie
						{
							Title = "Terminator",
							Description = "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine," +
							" sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's" +
							" future salvation.",
							Director = "James Cameron",
							MainActor = "Arnold Schwarzenegger, Linda Hamilton, Miachel Biehn",
							ReleaseDate = new DateTime(1984,1,1),
							Duration = 107,
							TicketPrice = 12
						},
						new Movie
						{
							Title = "Matrix",
							Description = "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking" +
							" truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
							Director = "Lana Wachowski, Lilly Wachowski",
							MainActor = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
							ReleaseDate = new DateTime(1999,1,1),
							Duration = 136,
							TicketPrice = 15
						},
						new Movie
						{
							Title = "Forrest Gump",
							Description = "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man" +
							" with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
							Director = "Robert Zemeckis",
							MainActor = "Tom Hanks, Robin Wright, Gary Sinise",
							ReleaseDate = new DateTime(1994,1,1),
							Duration = 144,
							TicketPrice = 13
						},
						new Movie
						{
							Title = "Pulp Fiction",
							Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in" +
							" four tales of violence and redemption.",
							Director = "Quentin Tarantino",
							MainActor = "John Travolta, Uma Thurman, Samuel L. Jackson",
							ReleaseDate = new DateTime(1994,1,1),
							Duration = 154,
							TicketPrice = 15
						},
						new Movie
						{
							Title = "Inception",
							Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task" +
							" of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
							Director = "Christopher Nolan",
							MainActor = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
							ReleaseDate = new DateTime(2010,1,1),
							Duration = 148,
							TicketPrice = 14
						},
						new Movie
						{
							Title = "Whiplash",
							Description = "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored" +
							" by an instructor who will stop at nothing to realize a student's potential.",
							Director = "Damien Chazelle",
							MainActor = "Miles Teller, J.K. Simmons, Melissa Benoist",
							ReleaseDate = new DateTime(2014,1,1),
							Duration = 106,
							TicketPrice = 12
						},
						new Movie
						{
							Title = "Apocalypse Now",
							Description = "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees " +
							"himself as a god.",
							Director = "Francis Ford Coppola",
							MainActor = "Martin Sheen, Marlon Brando, Robert Duvall",
							ReleaseDate = new DateTime(1979,1,1),
							Duration = 147,
							TicketPrice = 13
						},
					});
					db.SaveChanges();
				}

				if (!db.MovieGenres.Any())
				{
					db.MovieGenres.AddRange(new List<MovieGenre>
					{
						new MovieGenre { MovieId = 1, GenreId = 1 },
						new MovieGenre { MovieId = 1, GenreId = 8 },
						new MovieGenre { MovieId = 2, GenreId = 4 },
						new MovieGenre { MovieId = 2, GenreId = 6 },
						new MovieGenre { MovieId = 3, GenreId = 4 },
						new MovieGenre { MovieId = 3, GenreId = 6 },
						new MovieGenre { MovieId = 4, GenreId = 5 },
						new MovieGenre { MovieId = 4, GenreId = 9 },
						new MovieGenre { MovieId = 4, GenreId = 3 },
						new MovieGenre { MovieId = 5, GenreId = 5 },
						new MovieGenre { MovieId = 5, GenreId = 7 },
						new MovieGenre { MovieId = 6, GenreId = 4 },
						new MovieGenre { MovieId = 6, GenreId = 6 },
						new MovieGenre { MovieId = 7, GenreId = 5 },
						new MovieGenre { MovieId = 7, GenreId = 10 },
						new MovieGenre { MovieId = 8, GenreId = 5 },
						new MovieGenre { MovieId = 8, GenreId = 9 }
					});
					db.SaveChanges();
				}

				if (!db.Rooms.Any())
				{
					db.Rooms.AddRange(new List<Room>
					{
						new Room { Number = 1 },
						new Room { Number = 2 },
						new Room { Number = 3 },
						new Room { Number = 4 }
					});
					db.SaveChanges();
				}

				if (!db.Screenings.Any())
				{
					db.Screenings.AddRange(new List<Screening>
					{
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(9).AddMinutes(15), RoomId = 1},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(11).AddMinutes(0), RoomId = 1},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(12).AddMinutes(45), RoomId = 1},
						new Screening { MovieId = 4, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(14).AddMinutes(30), RoomId = 1},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(17).AddMinutes(15), RoomId = 1},
						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(20).AddMinutes(0), RoomId = 1},
						new Screening { MovieId = 2, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(22).AddMinutes(00), RoomId = 1},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(9).AddMinutes(15), RoomId = 1},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(11).AddMinutes(0), RoomId = 1},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(12).AddMinutes(45), RoomId = 1},
						new Screening { MovieId = 4, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(14).AddMinutes(30), RoomId = 1},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(17).AddMinutes(15), RoomId = 1},
						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(20).AddMinutes(0), RoomId = 1},
						new Screening { MovieId = 2, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(22).AddMinutes(00), RoomId = 1},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(9).AddMinutes(15), RoomId = 2},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(11).AddMinutes(0), RoomId = 2},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(12).AddMinutes(45), RoomId = 2},
						new Screening { MovieId = 3, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(15).AddMinutes(40), RoomId = 2},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(18).AddMinutes(15), RoomId = 2},
						new Screening { MovieId = 8, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(21).AddMinutes(0), RoomId = 2},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(9).AddMinutes(15), RoomId = 2},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(11).AddMinutes(0), RoomId = 2},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(12).AddMinutes(45), RoomId = 2},
						new Screening { MovieId = 3, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(15).AddMinutes(40), RoomId = 2},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(18).AddMinutes(15), RoomId = 2},
						new Screening { MovieId = 8, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(21).AddMinutes(0), RoomId = 2},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(9).AddMinutes(15), RoomId = 3},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(11).AddMinutes(0), RoomId = 3},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(12).AddMinutes(45), RoomId = 3},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(15).AddMinutes(30), RoomId = 3},
						new Screening { MovieId = 6, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(18).AddMinutes(15), RoomId = 3},
						new Screening { MovieId = 8, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(21).AddMinutes(0), RoomId = 3},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(9).AddMinutes(15), RoomId = 3},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(11).AddMinutes(0), RoomId = 3},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(12).AddMinutes(45), RoomId = 3},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(15).AddMinutes(30), RoomId = 3},
						new Screening { MovieId = 6, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(18).AddMinutes(15), RoomId = 3},
						new Screening { MovieId = 8, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(21).AddMinutes(0), RoomId = 3},

						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(9).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(11).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(13).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 4, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(16).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(19).AddMinutes(0), RoomId = 4},
						new Screening { MovieId = 2, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(22).AddMinutes(0), RoomId = 4},

						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(9).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(11).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(13).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 4, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(16).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(19).AddMinutes(0), RoomId = 4},
						new Screening { MovieId = 2, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(22).AddMinutes(0), RoomId = 4},
					});
					db.SaveChanges();
				}

				if (!db.Seats.Any())
				{
					db.Seats.AddRange(new List<Seat>
					{
						new Seat { Row = 1, Number = 1, RoomId = 1 },
						new Seat { Row = 1, Number = 2, RoomId = 1 },
						new Seat { Row = 1, Number = 3, RoomId = 1 },
						new Seat { Row = 1, Number = 4, RoomId = 1 },
						new Seat { Row = 1, Number = 5, RoomId = 1 },
						new Seat { Row = 1, Number = 6, RoomId = 1 },
						new Seat { Row = 1, Number = 7, RoomId = 1 },
						new Seat { Row = 1, Number = 8, RoomId = 1 },
						new Seat { Row = 1, Number = 9, RoomId = 1 },
						new Seat { Row = 1, Number = 10, RoomId = 1 },
						new Seat { Row = 1, Number = 11, RoomId = 1 },
						new Seat { Row = 1, Number = 12, RoomId = 1 },
						new Seat { Row = 1, Number = 13, RoomId = 1 },
						new Seat { Row = 1, Number = 14, RoomId = 1 },
						new Seat { Row = 1, Number = 15, RoomId = 1 },
						new Seat { Row = 1, Number = 16, RoomId = 1 },
						new Seat { Row = 2, Number = 1, RoomId = 1 },
						new Seat { Row = 2, Number = 2, RoomId = 1 },
						new Seat { Row = 2, Number = 3, RoomId = 1 },
						new Seat { Row = 2, Number = 4, RoomId = 1 },
						new Seat { Row = 2, Number = 5, RoomId = 1 },
						new Seat { Row = 2, Number = 6, RoomId = 1 },
						new Seat { Row = 2, Number = 7, RoomId = 1 },
						new Seat { Row = 2, Number = 8, RoomId = 1 },
						new Seat { Row = 2, Number = 9, RoomId = 1 },
						new Seat { Row = 2, Number = 10, RoomId = 1 },
						new Seat { Row = 2, Number = 11, RoomId = 1 },
						new Seat { Row = 2, Number = 12, RoomId = 1 },
						new Seat { Row = 2, Number = 13, RoomId = 1 },
						new Seat { Row = 2, Number = 14, RoomId = 1 },
						new Seat { Row = 2, Number = 15, RoomId = 1 },
						new Seat { Row = 2, Number = 16, RoomId = 1 },
						new Seat { Row = 3, Number = 1, RoomId = 1 },
						new Seat { Row = 3, Number = 2, RoomId = 1 },
						new Seat { Row = 3, Number = 3, RoomId = 1 },
						new Seat { Row = 3, Number = 4, RoomId = 1 },
						new Seat { Row = 3, Number = 5, RoomId = 1 },
						new Seat { Row = 3, Number = 6, RoomId = 1 },
						new Seat { Row = 3, Number = 7, RoomId = 1 },
						new Seat { Row = 3, Number = 8, RoomId = 1 },
						new Seat { Row = 3, Number = 9, RoomId = 1 },
						new Seat { Row = 3, Number = 10, RoomId = 1 },
						new Seat { Row = 3, Number = 11, RoomId = 1 },
						new Seat { Row = 3, Number = 12, RoomId = 1 },
						new Seat { Row = 3, Number = 13, RoomId = 1 },
						new Seat { Row = 3, Number = 14, RoomId = 1 },
						new Seat { Row = 3, Number = 15, RoomId = 1 },
						new Seat { Row = 3, Number = 16, RoomId = 1 },
						new Seat { Row = 4, Number = 1, RoomId = 1 },
						new Seat { Row = 4, Number = 2, RoomId = 1 },
						new Seat { Row = 4, Number = 3, RoomId = 1 },
						new Seat { Row = 4, Number = 4, RoomId = 1 },
						new Seat { Row = 4, Number = 5, RoomId = 1 },
						new Seat { Row = 4, Number = 6, RoomId = 1 },
						new Seat { Row = 4, Number = 7, RoomId = 1 },
						new Seat { Row = 4, Number = 8, RoomId = 1 },
						new Seat { Row = 4, Number = 9, RoomId = 1 },
						new Seat { Row = 4, Number = 10, RoomId = 1 },
						new Seat { Row = 4, Number = 11, RoomId = 1 },
						new Seat { Row = 4, Number = 12, RoomId = 1 },
						new Seat { Row = 4, Number = 13, RoomId = 1 },
						new Seat { Row = 4, Number = 14, RoomId = 1 },
						new Seat { Row = 4, Number = 15, RoomId = 1 },
						new Seat { Row = 4, Number = 16, RoomId = 1 },
						new Seat { Row = 5, Number = 1, RoomId = 1 },
						new Seat { Row = 5, Number = 2, RoomId = 1 },
						new Seat { Row = 5, Number = 3, RoomId = 1 },
						new Seat { Row = 5, Number = 4, RoomId = 1 },
						new Seat { Row = 5, Number = 5, RoomId = 1 },
						new Seat { Row = 5, Number = 6, RoomId = 1 },
						new Seat { Row = 5, Number = 7, RoomId = 1 },
						new Seat { Row = 5, Number = 8, RoomId = 1 },
						new Seat { Row = 5, Number = 9, RoomId = 1 },
						new Seat { Row = 5, Number = 10, RoomId = 1 },
						new Seat { Row = 5, Number = 11, RoomId = 1 },
						new Seat { Row = 5, Number = 12, RoomId = 1 },
						new Seat { Row = 5, Number = 13, RoomId = 1 },
						new Seat { Row = 5, Number = 14, RoomId = 1 },
						new Seat { Row = 5, Number = 15, RoomId = 1 },
						new Seat { Row = 5, Number = 16, RoomId = 1 },
						new Seat { Row = 6, Number = 1, RoomId = 1 },
						new Seat { Row = 6, Number = 2, RoomId = 1 },
						new Seat { Row = 6, Number = 3, RoomId = 1 },
						new Seat { Row = 6, Number = 4, RoomId = 1 },
						new Seat { Row = 6, Number = 5, RoomId = 1 },
						new Seat { Row = 6, Number = 6, RoomId = 1 },
						new Seat { Row = 6, Number = 7, RoomId = 1 },
						new Seat { Row = 6, Number = 8, RoomId = 1 },
						new Seat { Row = 6, Number = 9, RoomId = 1 },
						new Seat { Row = 6, Number = 10, RoomId = 1 },
						new Seat { Row = 6, Number = 11, RoomId = 1 },
						new Seat { Row = 6, Number = 12, RoomId = 1 },
						new Seat { Row = 6, Number = 13, RoomId = 1 },
						new Seat { Row = 6, Number = 14, RoomId = 1 },
						new Seat { Row = 6, Number = 15, RoomId = 1 },
						new Seat { Row = 6, Number = 16, RoomId = 1 },
						new Seat { Row = 7, Number = 1, RoomId = 1 },
						new Seat { Row = 7, Number = 2, RoomId = 1 },
						new Seat { Row = 7, Number = 3, RoomId = 1 },
						new Seat { Row = 7, Number = 4, RoomId = 1 },
						new Seat { Row = 7, Number = 5, RoomId = 1 },
						new Seat { Row = 7, Number = 6, RoomId = 1 },
						new Seat { Row = 7, Number = 7, RoomId = 1 },
						new Seat { Row = 7, Number = 8, RoomId = 1 },
						new Seat { Row = 7, Number = 9, RoomId = 1 },
						new Seat { Row = 7, Number = 10, RoomId = 1 },
						new Seat { Row = 7, Number = 11, RoomId = 1 },
						new Seat { Row = 7, Number = 12, RoomId = 1 },
						new Seat { Row = 7, Number = 13, RoomId = 1 },
						new Seat { Row = 7, Number = 14, RoomId = 1 },
						new Seat { Row = 7, Number = 15, RoomId = 1 },
						new Seat { Row = 7, Number = 16, RoomId = 1 },
						new Seat { Row = 8, Number = 1, RoomId = 1 },
						new Seat { Row = 8, Number = 2, RoomId = 1 },
						new Seat { Row = 8, Number = 3, RoomId = 1 },
						new Seat { Row = 8, Number = 4, RoomId = 1 },
						new Seat { Row = 8, Number = 5, RoomId = 1 },
						new Seat { Row = 8, Number = 6, RoomId = 1 },
						new Seat { Row = 8, Number = 7, RoomId = 1 },
						new Seat { Row = 8, Number = 8, RoomId = 1 },
						new Seat { Row = 8, Number = 9, RoomId = 1 },
						new Seat { Row = 8, Number = 10, RoomId = 1 },
						new Seat { Row = 8, Number = 11, RoomId = 1 },
						new Seat { Row = 8, Number = 12, RoomId = 1 },
						new Seat { Row = 8, Number = 13, RoomId = 1 },
						new Seat { Row = 8, Number = 14, RoomId = 1 },
						new Seat { Row = 8, Number = 15, RoomId = 1 },
						new Seat { Row = 8, Number = 16, RoomId = 1 },
						new Seat { Row = 9, Number = 1, RoomId = 1 },
						new Seat { Row = 9, Number = 2, RoomId = 1 },
						new Seat { Row = 9, Number = 3, RoomId = 1 },
						new Seat { Row = 9, Number = 4, RoomId = 1 },
						new Seat { Row = 9, Number = 5, RoomId = 1 },
						new Seat { Row = 9, Number = 6, RoomId = 1 },
						new Seat { Row = 9, Number = 7, RoomId = 1 },
						new Seat { Row = 9, Number = 8, RoomId = 1 },
						new Seat { Row = 9, Number = 9, RoomId = 1 },
						new Seat { Row = 9, Number = 10, RoomId = 1 },
						new Seat { Row = 9, Number = 11, RoomId = 1 },
						new Seat { Row = 9, Number = 12, RoomId = 1 },
						new Seat { Row = 9, Number = 13, RoomId = 1 },
						new Seat { Row = 9, Number = 14, RoomId = 1 },
						new Seat { Row = 9, Number = 15, RoomId = 1 },
						new Seat { Row = 9, Number = 16, RoomId = 1 },
						new Seat { Row = 10, Number = 1, RoomId = 1 },
						new Seat { Row = 10, Number = 2, RoomId = 1 },
						new Seat { Row = 10, Number = 3, RoomId = 1 },
						new Seat { Row = 10, Number = 4, RoomId = 1 },
						new Seat { Row = 10, Number = 5, RoomId = 1 },
						new Seat { Row = 10, Number = 6, RoomId = 1 },
						new Seat { Row = 10, Number = 7, RoomId = 1 },
						new Seat { Row = 10, Number = 8, RoomId = 1 },
						new Seat { Row = 10, Number = 9, RoomId = 1 },
						new Seat { Row = 10, Number = 10, RoomId = 1 },
						new Seat { Row = 10, Number = 11, RoomId = 1 },
						new Seat { Row = 10, Number = 12, RoomId = 1 },
						new Seat { Row = 10, Number = 13, RoomId = 1 },
						new Seat { Row = 10, Number = 14, RoomId = 1 },
						new Seat { Row = 10, Number = 15, RoomId = 1 },
						new Seat { Row = 10, Number = 16, RoomId = 1 },

						new Seat { Row = 1, Number = 1, RoomId = 2 },
						new Seat { Row = 1, Number = 2, RoomId = 2 },
						new Seat { Row = 1, Number = 3, RoomId = 2 },
						new Seat { Row = 1, Number = 4, RoomId = 2 },
						new Seat { Row = 1, Number = 5, RoomId = 2 },
						new Seat { Row = 1, Number = 6, RoomId = 2 },
						new Seat { Row = 1, Number = 7, RoomId = 2 },
						new Seat { Row = 1, Number = 8, RoomId = 2 },
						new Seat { Row = 1, Number = 9, RoomId = 2 },
						new Seat { Row = 1, Number = 10, RoomId = 2 },
						new Seat { Row = 1, Number = 11, RoomId = 2 },
						new Seat { Row = 1, Number = 12, RoomId = 2 },
						new Seat { Row = 1, Number = 13, RoomId = 2 },
						new Seat { Row = 1, Number = 14, RoomId = 2 },
						new Seat { Row = 1, Number = 15, RoomId = 2 },
						new Seat { Row = 1, Number = 16, RoomId = 2 },
						new Seat { Row = 2, Number = 1, RoomId = 2 },
						new Seat { Row = 2, Number = 2, RoomId = 2 },
						new Seat { Row = 2, Number = 3, RoomId = 2 },
						new Seat { Row = 2, Number = 4, RoomId = 2 },
						new Seat { Row = 2, Number = 5, RoomId = 2 },
						new Seat { Row = 2, Number = 6, RoomId = 2 },
						new Seat { Row = 2, Number = 7, RoomId = 2 },
						new Seat { Row = 2, Number = 8, RoomId = 2 },
						new Seat { Row = 2, Number = 9, RoomId = 2 },
						new Seat { Row = 2, Number = 10, RoomId = 2 },
						new Seat { Row = 2, Number = 11, RoomId = 2 },
						new Seat { Row = 2, Number = 12, RoomId = 2 },
						new Seat { Row = 2, Number = 13, RoomId = 2 },
						new Seat { Row = 2, Number = 14, RoomId = 2 },
						new Seat { Row = 2, Number = 15, RoomId = 2 },
						new Seat { Row = 2, Number = 16, RoomId = 2 },
						new Seat { Row = 3, Number = 1, RoomId = 2 },
						new Seat { Row = 3, Number = 2, RoomId = 2 },
						new Seat { Row = 3, Number = 3, RoomId = 2 },
						new Seat { Row = 3, Number = 4, RoomId = 2 },
						new Seat { Row = 3, Number = 5, RoomId = 2 },
						new Seat { Row = 3, Number = 6, RoomId = 2 },
						new Seat { Row = 3, Number = 7, RoomId = 2 },
						new Seat { Row = 3, Number = 8, RoomId = 2 },
						new Seat { Row = 3, Number = 9, RoomId = 2 },
						new Seat { Row = 3, Number = 10, RoomId = 2 },
						new Seat { Row = 3, Number = 11, RoomId = 2 },
						new Seat { Row = 3, Number = 12, RoomId = 2 },
						new Seat { Row = 3, Number = 13, RoomId = 2 },
						new Seat { Row = 3, Number = 14, RoomId = 2 },
						new Seat { Row = 3, Number = 15, RoomId = 2 },
						new Seat { Row = 3, Number = 16, RoomId = 2 },
						new Seat { Row = 4, Number = 1, RoomId = 2 },
						new Seat { Row = 4, Number = 2, RoomId = 2 },
						new Seat { Row = 4, Number = 3, RoomId = 2 },
						new Seat { Row = 4, Number = 4, RoomId = 2 },
						new Seat { Row = 4, Number = 5, RoomId = 2 },
						new Seat { Row = 4, Number = 6, RoomId = 2 },
						new Seat { Row = 4, Number = 7, RoomId = 2 },
						new Seat { Row = 4, Number = 8, RoomId = 2 },
						new Seat { Row = 4, Number = 9, RoomId = 2 },
						new Seat { Row = 4, Number = 10, RoomId = 2 },
						new Seat { Row = 4, Number = 11, RoomId = 2 },
						new Seat { Row = 4, Number = 12, RoomId = 2 },
						new Seat { Row = 4, Number = 13, RoomId = 2 },
						new Seat { Row = 4, Number = 14, RoomId = 2 },
						new Seat { Row = 4, Number = 15, RoomId = 2 },
						new Seat { Row = 4, Number = 16, RoomId = 2 },
						new Seat { Row = 5, Number = 1, RoomId = 2 },
						new Seat { Row = 5, Number = 2, RoomId = 2 },
						new Seat { Row = 5, Number = 3, RoomId = 2 },
						new Seat { Row = 5, Number = 4, RoomId = 2 },
						new Seat { Row = 5, Number = 5, RoomId = 2 },
						new Seat { Row = 5, Number = 6, RoomId = 2 },
						new Seat { Row = 5, Number = 7, RoomId = 2 },
						new Seat { Row = 5, Number = 8, RoomId = 2 },
						new Seat { Row = 5, Number = 9, RoomId = 2 },
						new Seat { Row = 5, Number = 10, RoomId = 2 },
						new Seat { Row = 5, Number = 11, RoomId = 2 },
						new Seat { Row = 5, Number = 12, RoomId = 2 },
						new Seat { Row = 5, Number = 13, RoomId = 2 },
						new Seat { Row = 5, Number = 14, RoomId = 2 },
						new Seat { Row = 5, Number = 15, RoomId = 2 },
						new Seat { Row = 5, Number = 16, RoomId = 2 },
						new Seat { Row = 6, Number = 1, RoomId = 2 },
						new Seat { Row = 6, Number = 2, RoomId = 2 },
						new Seat { Row = 6, Number = 3, RoomId = 2 },
						new Seat { Row = 6, Number = 4, RoomId = 2 },
						new Seat { Row = 6, Number = 5, RoomId = 2 },
						new Seat { Row = 6, Number = 6, RoomId = 2 },
						new Seat { Row = 6, Number = 7, RoomId = 2 },
						new Seat { Row = 6, Number = 8, RoomId = 2 },
						new Seat { Row = 6, Number = 9, RoomId = 2 },
						new Seat { Row = 6, Number = 10, RoomId = 2 },
						new Seat { Row = 6, Number = 11, RoomId = 2 },
						new Seat { Row = 6, Number = 12, RoomId = 2 },
						new Seat { Row = 6, Number = 13, RoomId = 2 },
						new Seat { Row = 6, Number = 14, RoomId = 2 },
						new Seat { Row = 6, Number = 15, RoomId = 2 },
						new Seat { Row = 6, Number = 16, RoomId = 2 },
						new Seat { Row = 7, Number = 1, RoomId = 2 },
						new Seat { Row = 7, Number = 2, RoomId = 2 },
						new Seat { Row = 7, Number = 3, RoomId = 2 },
						new Seat { Row = 7, Number = 4, RoomId = 2 },
						new Seat { Row = 7, Number = 5, RoomId = 2 },
						new Seat { Row = 7, Number = 6, RoomId = 2 },
						new Seat { Row = 7, Number = 7, RoomId = 2 },
						new Seat { Row = 7, Number = 8, RoomId = 2 },
						new Seat { Row = 7, Number = 9, RoomId = 2 },
						new Seat { Row = 7, Number = 10, RoomId = 2 },
						new Seat { Row = 7, Number = 11, RoomId = 2 },
						new Seat { Row = 7, Number = 12, RoomId = 2 },
						new Seat { Row = 7, Number = 13, RoomId = 2 },
						new Seat { Row = 7, Number = 14, RoomId = 2 },
						new Seat { Row = 7, Number = 15, RoomId = 2 },
						new Seat { Row = 7, Number = 16, RoomId = 2 },
						new Seat { Row = 8, Number = 1, RoomId = 2 },
						new Seat { Row = 8, Number = 2, RoomId = 2 },
						new Seat { Row = 8, Number = 3, RoomId = 2 },
						new Seat { Row = 8, Number = 4, RoomId = 2 },
						new Seat { Row = 8, Number = 5, RoomId = 2 },
						new Seat { Row = 8, Number = 6, RoomId = 2 },
						new Seat { Row = 8, Number = 7, RoomId = 2 },
						new Seat { Row = 8, Number = 8, RoomId = 2 },
						new Seat { Row = 8, Number = 9, RoomId = 2 },
						new Seat { Row = 8, Number = 10, RoomId = 2 },
						new Seat { Row = 8, Number = 11, RoomId = 2 },
						new Seat { Row = 8, Number = 12, RoomId = 2 },
						new Seat { Row = 8, Number = 13, RoomId = 2 },
						new Seat { Row = 8, Number = 14, RoomId = 2 },
						new Seat { Row = 8, Number = 15, RoomId = 2 },
						new Seat { Row = 8, Number = 16, RoomId = 2 },
						new Seat { Row = 9, Number = 1, RoomId = 2 },
						new Seat { Row = 9, Number = 2, RoomId = 2 },
						new Seat { Row = 9, Number = 3, RoomId = 2 },
						new Seat { Row = 9, Number = 4, RoomId = 2 },
						new Seat { Row = 9, Number = 5, RoomId = 2 },
						new Seat { Row = 9, Number = 6, RoomId = 2 },
						new Seat { Row = 9, Number = 7, RoomId = 2 },
						new Seat { Row = 9, Number = 8, RoomId = 2 },
						new Seat { Row = 9, Number = 9, RoomId = 2 },
						new Seat { Row = 9, Number = 10, RoomId = 2 },
						new Seat { Row = 9, Number = 11, RoomId = 2 },
						new Seat { Row = 9, Number = 12, RoomId = 2 },
						new Seat { Row = 9, Number = 13, RoomId = 2 },
						new Seat { Row = 9, Number = 14, RoomId = 2 },
						new Seat { Row = 9, Number = 15, RoomId = 2 },
						new Seat { Row = 9, Number = 16, RoomId = 2 },
						new Seat { Row = 10, Number = 1, RoomId = 2 },
						new Seat { Row = 10, Number = 2, RoomId = 2 },
						new Seat { Row = 10, Number = 3, RoomId = 2 },
						new Seat { Row = 10, Number = 4, RoomId = 2 },
						new Seat { Row = 10, Number = 5, RoomId = 2 },
						new Seat { Row = 10, Number = 6, RoomId = 2 },
						new Seat { Row = 10, Number = 7, RoomId = 2 },
						new Seat { Row = 10, Number = 8, RoomId = 2 },
						new Seat { Row = 10, Number = 9, RoomId = 2 },
						new Seat { Row = 10, Number = 10, RoomId = 2 },
						new Seat { Row = 10, Number = 11, RoomId = 2 },
						new Seat { Row = 10, Number = 12, RoomId = 2 },
						new Seat { Row = 10, Number = 13, RoomId = 2 },
						new Seat { Row = 10, Number = 14, RoomId = 2 },
						new Seat { Row = 10, Number = 15, RoomId = 2 },
						new Seat { Row = 10, Number = 16, RoomId = 2 },

						new Seat { Row = 1, Number = 1, RoomId = 3 },
						new Seat { Row = 1, Number = 2, RoomId = 3 },
						new Seat { Row = 1, Number = 3, RoomId = 3 },
						new Seat { Row = 1, Number = 4, RoomId = 3 },
						new Seat { Row = 1, Number = 5, RoomId = 3 },
						new Seat { Row = 1, Number = 6, RoomId = 3 },
						new Seat { Row = 1, Number = 7, RoomId = 3 },
						new Seat { Row = 1, Number = 8, RoomId = 3 },
						new Seat { Row = 1, Number = 9, RoomId = 3 },
						new Seat { Row = 1, Number = 10, RoomId = 3 },
						new Seat { Row = 1, Number = 11, RoomId = 3 },
						new Seat { Row = 1, Number = 12, RoomId = 3 },
						new Seat { Row = 1, Number = 13, RoomId = 3 },
						new Seat { Row = 1, Number = 14, RoomId = 3 },
						new Seat { Row = 1, Number = 15, RoomId = 3 },
						new Seat { Row = 1, Number = 16, RoomId = 3 },
						new Seat { Row = 2, Number = 1, RoomId = 3 },
						new Seat { Row = 2, Number = 2, RoomId = 3 },
						new Seat { Row = 2, Number = 3, RoomId = 3 },
						new Seat { Row = 2, Number = 4, RoomId = 3 },
						new Seat { Row = 2, Number = 5, RoomId = 3 },
						new Seat { Row = 2, Number = 6, RoomId = 3 },
						new Seat { Row = 2, Number = 7, RoomId = 3 },
						new Seat { Row = 2, Number = 8, RoomId = 3 },
						new Seat { Row = 2, Number = 9, RoomId = 3 },
						new Seat { Row = 2, Number = 10, RoomId = 3 },
						new Seat { Row = 2, Number = 11, RoomId = 3 },
						new Seat { Row = 2, Number = 12, RoomId = 3 },
						new Seat { Row = 2, Number = 13, RoomId = 3 },
						new Seat { Row = 2, Number = 14, RoomId = 3 },
						new Seat { Row = 2, Number = 15, RoomId = 3 },
						new Seat { Row = 2, Number = 16, RoomId = 3 },
						new Seat { Row = 3, Number = 1, RoomId = 3 },
						new Seat { Row = 3, Number = 2, RoomId = 3 },
						new Seat { Row = 3, Number = 3, RoomId = 3 },
						new Seat { Row = 3, Number = 4, RoomId = 3 },
						new Seat { Row = 3, Number = 5, RoomId = 3 },
						new Seat { Row = 3, Number = 6, RoomId = 3 },
						new Seat { Row = 3, Number = 7, RoomId = 3 },
						new Seat { Row = 3, Number = 8, RoomId = 3 },
						new Seat { Row = 3, Number = 9, RoomId = 3 },
						new Seat { Row = 3, Number = 10, RoomId = 3 },
						new Seat { Row = 3, Number = 11, RoomId = 3 },
						new Seat { Row = 3, Number = 12, RoomId = 3 },
						new Seat { Row = 3, Number = 13, RoomId = 3 },
						new Seat { Row = 3, Number = 14, RoomId = 3 },
						new Seat { Row = 3, Number = 15, RoomId = 3 },
						new Seat { Row = 3, Number = 16, RoomId = 3 },
						new Seat { Row = 4, Number = 1, RoomId = 3 },
						new Seat { Row = 4, Number = 2, RoomId = 3 },
						new Seat { Row = 4, Number = 3, RoomId = 3 },
						new Seat { Row = 4, Number = 4, RoomId = 3 },
						new Seat { Row = 4, Number = 5, RoomId = 3 },
						new Seat { Row = 4, Number = 6, RoomId = 3 },
						new Seat { Row = 4, Number = 7, RoomId = 3 },
						new Seat { Row = 4, Number = 8, RoomId = 3 },
						new Seat { Row = 4, Number = 9, RoomId = 3 },
						new Seat { Row = 4, Number = 10, RoomId = 3 },
						new Seat { Row = 4, Number = 11, RoomId = 3 },
						new Seat { Row = 4, Number = 12, RoomId = 3 },
						new Seat { Row = 4, Number = 13, RoomId = 3 },
						new Seat { Row = 4, Number = 14, RoomId = 3 },
						new Seat { Row = 4, Number = 15, RoomId = 3 },
						new Seat { Row = 4, Number = 16, RoomId = 3 },
						new Seat { Row = 5, Number = 1, RoomId = 3 },
						new Seat { Row = 5, Number = 2, RoomId = 3 },
						new Seat { Row = 5, Number = 3, RoomId = 3 },
						new Seat { Row = 5, Number = 4, RoomId = 3 },
						new Seat { Row = 5, Number = 5, RoomId = 3 },
						new Seat { Row = 5, Number = 6, RoomId = 3 },
						new Seat { Row = 5, Number = 7, RoomId = 3 },
						new Seat { Row = 5, Number = 8, RoomId = 3 },
						new Seat { Row = 5, Number = 9, RoomId = 3 },
						new Seat { Row = 5, Number = 10, RoomId = 3 },
						new Seat { Row = 5, Number = 11, RoomId = 3 },
						new Seat { Row = 5, Number = 12, RoomId = 3 },
						new Seat { Row = 5, Number = 13, RoomId = 3 },
						new Seat { Row = 5, Number = 14, RoomId = 3 },
						new Seat { Row = 5, Number = 15, RoomId = 3 },
						new Seat { Row = 5, Number = 16, RoomId = 3 },
						new Seat { Row = 6, Number = 1, RoomId = 3 },
						new Seat { Row = 6, Number = 2, RoomId = 3 },
						new Seat { Row = 6, Number = 3, RoomId = 3 },
						new Seat { Row = 6, Number = 4, RoomId = 3 },
						new Seat { Row = 6, Number = 5, RoomId = 3 },
						new Seat { Row = 6, Number = 6, RoomId = 3 },
						new Seat { Row = 6, Number = 7, RoomId = 3 },
						new Seat { Row = 6, Number = 8, RoomId = 3 },
						new Seat { Row = 6, Number = 9, RoomId = 3 },
						new Seat { Row = 6, Number = 10, RoomId = 3 },
						new Seat { Row = 6, Number = 11, RoomId = 3 },
						new Seat { Row = 6, Number = 12, RoomId = 3 },
						new Seat { Row = 6, Number = 13, RoomId = 3 },
						new Seat { Row = 6, Number = 14, RoomId = 3 },
						new Seat { Row = 6, Number = 15, RoomId = 3 },
						new Seat { Row = 6, Number = 16, RoomId = 3 },
						new Seat { Row = 7, Number = 1, RoomId = 3 },
						new Seat { Row = 7, Number = 2, RoomId = 3 },
						new Seat { Row = 7, Number = 3, RoomId = 3 },
						new Seat { Row = 7, Number = 4, RoomId = 3 },
						new Seat { Row = 7, Number = 5, RoomId = 3 },
						new Seat { Row = 7, Number = 6, RoomId = 3 },
						new Seat { Row = 7, Number = 7, RoomId = 3 },
						new Seat { Row = 7, Number = 8, RoomId = 3 },
						new Seat { Row = 7, Number = 9, RoomId = 3 },
						new Seat { Row = 7, Number = 10, RoomId = 3 },
						new Seat { Row = 7, Number = 11, RoomId = 3 },
						new Seat { Row = 7, Number = 12, RoomId = 3 },
						new Seat { Row = 7, Number = 13, RoomId = 3 },
						new Seat { Row = 7, Number = 14, RoomId = 3 },
						new Seat { Row = 7, Number = 15, RoomId = 3 },
						new Seat { Row = 7, Number = 16, RoomId = 3 },
						new Seat { Row = 8, Number = 1, RoomId = 3 },
						new Seat { Row = 8, Number = 2, RoomId = 3 },
						new Seat { Row = 8, Number = 3, RoomId = 3 },
						new Seat { Row = 8, Number = 4, RoomId = 3 },
						new Seat { Row = 8, Number = 5, RoomId = 3 },
						new Seat { Row = 8, Number = 6, RoomId = 3 },
						new Seat { Row = 8, Number = 7, RoomId = 3 },
						new Seat { Row = 8, Number = 8, RoomId = 3 },
						new Seat { Row = 8, Number = 9, RoomId = 3 },
						new Seat { Row = 8, Number = 10, RoomId = 3 },
						new Seat { Row = 8, Number = 11, RoomId = 3 },
						new Seat { Row = 8, Number = 12, RoomId = 3 },
						new Seat { Row = 8, Number = 13, RoomId = 3 },
						new Seat { Row = 8, Number = 14, RoomId = 3 },
						new Seat { Row = 8, Number = 15, RoomId = 3 },
						new Seat { Row = 8, Number = 16, RoomId = 3 },
						new Seat { Row = 9, Number = 1, RoomId = 3 },
						new Seat { Row = 9, Number = 2, RoomId = 3 },
						new Seat { Row = 9, Number = 3, RoomId = 3 },
						new Seat { Row = 9, Number = 4, RoomId = 3 },
						new Seat { Row = 9, Number = 5, RoomId = 3 },
						new Seat { Row = 9, Number = 6, RoomId = 3 },
						new Seat { Row = 9, Number = 7, RoomId = 3 },
						new Seat { Row = 9, Number = 8, RoomId = 3 },
						new Seat { Row = 9, Number = 9, RoomId = 3 },
						new Seat { Row = 9, Number = 10, RoomId = 3 },
						new Seat { Row = 9, Number = 11, RoomId = 3 },
						new Seat { Row = 9, Number = 12, RoomId = 3 },
						new Seat { Row = 9, Number = 13, RoomId = 3 },
						new Seat { Row = 9, Number = 14, RoomId = 3 },
						new Seat { Row = 9, Number = 15, RoomId = 3 },
						new Seat { Row = 9, Number = 16, RoomId = 3 },
						new Seat { Row = 10, Number = 1, RoomId = 3 },
						new Seat { Row = 10, Number = 2, RoomId = 3 },
						new Seat { Row = 10, Number = 3, RoomId = 3 },
						new Seat { Row = 10, Number = 4, RoomId = 3 },
						new Seat { Row = 10, Number = 5, RoomId = 3 },
						new Seat { Row = 10, Number = 6, RoomId = 3 },
						new Seat { Row = 10, Number = 7, RoomId = 3 },
						new Seat { Row = 10, Number = 8, RoomId = 3 },
						new Seat { Row = 10, Number = 9, RoomId = 3 },
						new Seat { Row = 10, Number = 10, RoomId = 3 },
						new Seat { Row = 10, Number = 11, RoomId = 3 },
						new Seat { Row = 10, Number = 12, RoomId = 3 },
						new Seat { Row = 10, Number = 13, RoomId = 3 },
						new Seat { Row = 10, Number = 14, RoomId = 3 },
						new Seat { Row = 10, Number = 15, RoomId = 3 },
						new Seat { Row = 10, Number = 16, RoomId = 3 },

						new Seat { Row = 1, Number = 1, RoomId = 4 },
						new Seat { Row = 1, Number = 2, RoomId = 4 },
						new Seat { Row = 1, Number = 3, RoomId = 4 },
						new Seat { Row = 1, Number = 4, RoomId = 4 },
						new Seat { Row = 1, Number = 5, RoomId = 4 },
						new Seat { Row = 1, Number = 6, RoomId = 4 },
						new Seat { Row = 1, Number = 7, RoomId = 4 },
						new Seat { Row = 1, Number = 8, RoomId = 4 },
						new Seat { Row = 1, Number = 9, RoomId = 4 },
						new Seat { Row = 1, Number = 10, RoomId = 4 },
						new Seat { Row = 1, Number = 11, RoomId = 4 },
						new Seat { Row = 1, Number = 12, RoomId = 4 },
						new Seat { Row = 1, Number = 13, RoomId = 4 },
						new Seat { Row = 1, Number = 14, RoomId = 4 },
						new Seat { Row = 1, Number = 15, RoomId = 4 },
						new Seat { Row = 1, Number = 16, RoomId = 4 },
						new Seat { Row = 2, Number = 1, RoomId = 4 },
						new Seat { Row = 2, Number = 2, RoomId = 4 },
						new Seat { Row = 2, Number = 3, RoomId = 4 },
						new Seat { Row = 2, Number = 4, RoomId = 4 },
						new Seat { Row = 2, Number = 5, RoomId = 4 },
						new Seat { Row = 2, Number = 6, RoomId = 4 },
						new Seat { Row = 2, Number = 7, RoomId = 4 },
						new Seat { Row = 2, Number = 8, RoomId = 4 },
						new Seat { Row = 2, Number = 9, RoomId = 4 },
						new Seat { Row = 2, Number = 10, RoomId = 4 },
						new Seat { Row = 2, Number = 11, RoomId = 4 },
						new Seat { Row = 2, Number = 12, RoomId = 4 },
						new Seat { Row = 2, Number = 13, RoomId = 4 },
						new Seat { Row = 2, Number = 14, RoomId = 4 },
						new Seat { Row = 2, Number = 15, RoomId = 4 },
						new Seat { Row = 2, Number = 16, RoomId = 4 },
						new Seat { Row = 3, Number = 1, RoomId = 4 },
						new Seat { Row = 3, Number = 2, RoomId = 4 },
						new Seat { Row = 3, Number = 3, RoomId = 4 },
						new Seat { Row = 3, Number = 4, RoomId = 4 },
						new Seat { Row = 3, Number = 5, RoomId = 4 },
						new Seat { Row = 3, Number = 6, RoomId = 4 },
						new Seat { Row = 3, Number = 7, RoomId = 4 },
						new Seat { Row = 3, Number = 8, RoomId = 4 },
						new Seat { Row = 3, Number = 9, RoomId = 4 },
						new Seat { Row = 3, Number = 10, RoomId = 4 },
						new Seat { Row = 3, Number = 11, RoomId = 4 },
						new Seat { Row = 3, Number = 12, RoomId = 4 },
						new Seat { Row = 3, Number = 13, RoomId = 4 },
						new Seat { Row = 3, Number = 14, RoomId = 4 },
						new Seat { Row = 3, Number = 15, RoomId = 4 },
						new Seat { Row = 3, Number = 16, RoomId = 4 },
						new Seat { Row = 4, Number = 1, RoomId = 4 },
						new Seat { Row = 4, Number = 2, RoomId = 4 },
						new Seat { Row = 4, Number = 3, RoomId = 4 },
						new Seat { Row = 4, Number = 4, RoomId = 4 },
						new Seat { Row = 4, Number = 5, RoomId = 4 },
						new Seat { Row = 4, Number = 6, RoomId = 4 },
						new Seat { Row = 4, Number = 7, RoomId = 4 },
						new Seat { Row = 4, Number = 8, RoomId = 4 },
						new Seat { Row = 4, Number = 9, RoomId = 4 },
						new Seat { Row = 4, Number = 10, RoomId = 4 },
						new Seat { Row = 4, Number = 11, RoomId = 4 },
						new Seat { Row = 4, Number = 12, RoomId = 4 },
						new Seat { Row = 4, Number = 13, RoomId = 4 },
						new Seat { Row = 4, Number = 14, RoomId = 4 },
						new Seat { Row = 4, Number = 15, RoomId = 4 },
						new Seat { Row = 4, Number = 16, RoomId = 4 },
						new Seat { Row = 5, Number = 1, RoomId = 4 },
						new Seat { Row = 5, Number = 2, RoomId = 4 },
						new Seat { Row = 5, Number = 3, RoomId = 4 },
						new Seat { Row = 5, Number = 4, RoomId = 4 },
						new Seat { Row = 5, Number = 5, RoomId = 4 },
						new Seat { Row = 5, Number = 6, RoomId = 4 },
						new Seat { Row = 5, Number = 7, RoomId = 4 },
						new Seat { Row = 5, Number = 8, RoomId = 4 },
						new Seat { Row = 5, Number = 9, RoomId = 4 },
						new Seat { Row = 5, Number = 10, RoomId = 4 },
						new Seat { Row = 5, Number = 11, RoomId = 4 },
						new Seat { Row = 5, Number = 12, RoomId = 4 },
						new Seat { Row = 5, Number = 13, RoomId = 4 },
						new Seat { Row = 5, Number = 14, RoomId = 4 },
						new Seat { Row = 5, Number = 15, RoomId = 4 },
						new Seat { Row = 5, Number = 16, RoomId = 4 },
						new Seat { Row = 6, Number = 1, RoomId = 4 },
						new Seat { Row = 6, Number = 2, RoomId = 4 },
						new Seat { Row = 6, Number = 3, RoomId = 4 },
						new Seat { Row = 6, Number = 4, RoomId = 4 },
						new Seat { Row = 6, Number = 5, RoomId = 4 },
						new Seat { Row = 6, Number = 6, RoomId = 4 },
						new Seat { Row = 6, Number = 7, RoomId = 4 },
						new Seat { Row = 6, Number = 8, RoomId = 4 },
						new Seat { Row = 6, Number = 9, RoomId = 4 },
						new Seat { Row = 6, Number = 10, RoomId = 4 },
						new Seat { Row = 6, Number = 11, RoomId = 4 },
						new Seat { Row = 6, Number = 12, RoomId = 4 },
						new Seat { Row = 6, Number = 13, RoomId = 4 },
						new Seat { Row = 6, Number = 14, RoomId = 4 },
						new Seat { Row = 6, Number = 15, RoomId = 4 },
						new Seat { Row = 6, Number = 16, RoomId = 4 },
						new Seat { Row = 7, Number = 1, RoomId = 4 },
						new Seat { Row = 7, Number = 2, RoomId = 4 },
						new Seat { Row = 7, Number = 3, RoomId = 4 },
						new Seat { Row = 7, Number = 4, RoomId = 4 },
						new Seat { Row = 7, Number = 5, RoomId = 4 },
						new Seat { Row = 7, Number = 6, RoomId = 4 },
						new Seat { Row = 7, Number = 7, RoomId = 4 },
						new Seat { Row = 7, Number = 8, RoomId = 4 },
						new Seat { Row = 7, Number = 9, RoomId = 4 },
						new Seat { Row = 7, Number = 10, RoomId = 4 },
						new Seat { Row = 7, Number = 11, RoomId = 4 },
						new Seat { Row = 7, Number = 12, RoomId = 4 },
						new Seat { Row = 7, Number = 13, RoomId = 4 },
						new Seat { Row = 7, Number = 14, RoomId = 4 },
						new Seat { Row = 7, Number = 15, RoomId = 4 },
						new Seat { Row = 7, Number = 16, RoomId = 4 },
						new Seat { Row = 8, Number = 1, RoomId = 4 },
						new Seat { Row = 8, Number = 2, RoomId = 4 },
						new Seat { Row = 8, Number = 3, RoomId = 4 },
						new Seat { Row = 8, Number = 4, RoomId = 4 },
						new Seat { Row = 8, Number = 5, RoomId = 4 },
						new Seat { Row = 8, Number = 6, RoomId = 4 },
						new Seat { Row = 8, Number = 7, RoomId = 4 },
						new Seat { Row = 8, Number = 8, RoomId = 4 },
						new Seat { Row = 8, Number = 9, RoomId = 4 },
						new Seat { Row = 8, Number = 10, RoomId = 4 },
						new Seat { Row = 8, Number = 11, RoomId = 4 },
						new Seat { Row = 8, Number = 12, RoomId = 4 },
						new Seat { Row = 8, Number = 13, RoomId = 4 },
						new Seat { Row = 8, Number = 14, RoomId = 4 },
						new Seat { Row = 8, Number = 15, RoomId = 4 },
						new Seat { Row = 8, Number = 16, RoomId = 4 },
						new Seat { Row = 9, Number = 1, RoomId = 4 },
						new Seat { Row = 9, Number = 2, RoomId = 4 },
						new Seat { Row = 9, Number = 3, RoomId = 4 },
						new Seat { Row = 9, Number = 4, RoomId = 4 },
						new Seat { Row = 9, Number = 5, RoomId = 4 },
						new Seat { Row = 9, Number = 6, RoomId = 4 },
						new Seat { Row = 9, Number = 7, RoomId = 4 },
						new Seat { Row = 9, Number = 8, RoomId = 4 },
						new Seat { Row = 9, Number = 9, RoomId = 4 },
						new Seat { Row = 9, Number = 10, RoomId = 4 },
						new Seat { Row = 9, Number = 11, RoomId = 4 },
						new Seat { Row = 9, Number = 12, RoomId = 4 },
						new Seat { Row = 9, Number = 13, RoomId = 4 },
						new Seat { Row = 9, Number = 14, RoomId = 4 },
						new Seat { Row = 9, Number = 15, RoomId = 4 },
						new Seat { Row = 9, Number = 16, RoomId = 4 },
						new Seat { Row = 10, Number = 1, RoomId = 4 },
						new Seat { Row = 10, Number = 2, RoomId = 4 },
						new Seat { Row = 10, Number = 3, RoomId = 4 },
						new Seat { Row = 10, Number = 4, RoomId = 4 },
						new Seat { Row = 10, Number = 5, RoomId = 4 },
						new Seat { Row = 10, Number = 6, RoomId = 4 },
						new Seat { Row = 10, Number = 7, RoomId = 4 },
						new Seat { Row = 10, Number = 8, RoomId = 4 },
						new Seat { Row = 10, Number = 9, RoomId = 4 },
						new Seat { Row = 10, Number = 10, RoomId = 4 },
						new Seat { Row = 10, Number = 11, RoomId = 4 },
						new Seat { Row = 10, Number = 12, RoomId = 4 },
						new Seat { Row = 10, Number = 13, RoomId = 4 },
						new Seat { Row = 10, Number = 14, RoomId = 4 },
						new Seat { Row = 10, Number = 15, RoomId = 4 },
						new Seat { Row = 10, Number = 16, RoomId = 4 }
					});
					db.SaveChanges();
				}
			}
		}
	}
}
