using CinemaApp.DataAccess.Data;
using CinemaApp.Models.DomainModels;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace CinemaApp.DataAccess.Seed
{
    public class AddDbInitializer
	{
		public static void Seed(IApplicationBuilder applicationBuilder)
		{
			using (var serviceScope = applicationBuilder.ApplicationServices.CreateScope())
			{
				var db = serviceScope.ServiceProvider.GetService<ApplicationDbContext>();
				
				db.Database.EnsureCreated();

				if (!db.Users.Any())
				{
					db.Users.Add(new ApplicationUser
					{
						UserName = "test@mail.com",
						NormalizedUserName = "TEST@MAIL.COM",
						Email = "test@mail.com",
						NormalizedEmail = "TEST@MAIL.COM",
						EmailConfirmed = false,
						PasswordHash = "AQAAAAIAAYagAAAAED3yoUiTqg90DI5VEgi6SOuEssQWEa8HtUd9ava6I4E4Wp9yb0e/TzxRberNLhY7Vw==",
						SecurityStamp = "OTFGDWUBEYEOXHCWGJU4PDSVJ4LXRD5U",
						ConcurrencyStamp = "1421ce5b-96f1-472b-9ff3-aeb04b6e5a76",
						PhoneNumber = "111222333",
						PhoneNumberConfirmed = false,
						TwoFactorEnabled = false,
						LockoutEnd = null,
						LockoutEnabled = true,
						AccessFailedCount = 0,
						FirstName = "Jan",
						LastName = "Nowak",
						StartJob = DateTime.Today
					});
					db.SaveChanges();
				}

				if(!db.Roles.Any())
				{
					db.Roles.Add(new Microsoft.AspNetCore.Identity.IdentityRole
					{
						Name = "Employee",
						NormalizedName = "EMPLOYEE",
						ConcurrencyStamp = null
					});
					db.SaveChanges();
				}

				if(!db.UserRoles.Any())
				{
					db.UserRoles.Add(new Microsoft.AspNetCore.Identity.IdentityUserRole<string>
					{
						UserId = db.ApplicationUsers.First().Id,
						RoleId = db.Roles.First().Id
					});
					db.SaveChanges();
				}

				if (!db.HomeContents.Any())
				{
					db.HomeContents.AddRange(new List<HomeContent>
					{
						new HomeContent
						{
							CarouselImgUrl_1 = @"\images\carousel\7f2ee018-c1ef-4249-925a-cc6ba3b982e0.jpg",
							CarouselImgUrl_2 = @"\images\carousel\6ccd8c10-9a18-479f-b933-71737d268418.jpg",
							CarouselImgUrl_3 = @"\images\carousel\26829825-35b9-433a-8b97-bdbd2e616683.jpg",
							BlogTitle_1 = "We believe that",
							BlogTitle_2 = "What's new?",
							BlogTitle_3 = "See unseen",
							BlogContent_1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dictum aliquet augue eu efficitur. " +
							"Quisque molestie diam eros, ac sagittis diam sodales et. Donec orci sem, ornare vel nibh sed, imperdiet tempus orci. " +
							"Donec bibendum ex justo, sed hendrerit enim hendrerit vel. Ut accumsan blandit sem quis convallis. Nulla sit amet lobortis" +
							" ipsum. Curabitur condimentum, neque id convallis accumsan, lorem nunc malesuada neque, id mattis orci lectus at lacus." +
							" Quisque pretium turpis congue ultrices viverra. Mauris sagittis ut arcu vel suscipit. Donec consectetur elit et faucibus " +
							"finibus. Quisque quis hendrerit nunc, vitae pulvinar lectus. Vivamus tincidunt sodales nulla. Vestibulum quis mi sapien. " +
							"Nunc erat orci, venenatis id dictum sit amet, ullamcorper nec ex. ",
							BlogContent_2 = "Etiam pellentesque, augue ac malesuada consequat, purus arcu dapibus ligula, nec maximus nisi mauris sit amet " +
							"libero. In et libero ultricies quam consequat tempus et id dolor. Donec sed sapien lorem. Donec tristique efficitur imperdiet." +
							" Sed in erat vel sem tincidunt posuere. Vestibulum cursus turpis nec erat commodo varius. Aliquam felis justo, tincidunt ac" +
							" sodales vitae, consequat non arcu. Praesent scelerisque gravida dolor, vitae molestie nunc pellentesque eget. Nunc posuere " +
							"eu erat at varius. ",
							BlogContent_3 = "Nunc eu tortor tortor. In tempor lobortis metus ac fringilla. Etiam fermentum dolor mollis, vehicula metus" +
							" quis, semper nibh. Duis at pellentesque arcu. Praesent maximus neque eu eros pharetra pharetra. Ut at mi non tellus posuere" +
							" molestie non eget massa. Suspendisse potenti. Donec felis tortor, hendrerit quis vestibulum a, scelerisque vel neque. " +
							"Aliquam nec varius erat. Pellentesque tellus justo, viverra quis mi et, convallis ultricies nunc. Mauris nec ex sed elit" +
							" posuere mattis. Maecenas et elit nunc. Donec dictum sollicitudin ipsum, eu mattis metus auctor in. Nam id diam in ante " +
							"pharetra viverra. Fusce pretium bibendum augue, id scelerisque arcu consequat non. "
						}
					});
					db.SaveChanges();
				}

				if (!db.Genres.Any())
				{
					db.Genres.AddRange(new List<Genre>
					{
						new Genre { Name = "Comedy" },
						new Genre { Name = "Thriller" },
						new Genre { Name = "Romance" },
						new Genre { Name = "Sci-Fi" },
						new Genre { Name = "Drama" },
						new Genre { Name = "Action" },
						new Genre { Name = "Crime" },
						new Genre { Name = "Animation" },
						new Genre { Name = "War" },
						new Genre { Name = "Music" }
					});
					db.SaveChanges();
				}

				if (!db.Movies.Any())
				{
					db.Movies.AddRange(new List<Movie>
					{
						new Movie
						{
							Title = "Shrek",
							Description = "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, " +
							"who must go on a quest and rescue a princess for the lord in order to get his land back.",
							Director = "Andrev Adamson, Vicky Jenson",
							MainActor = "Mike Meyers, Eddie Murphy, Cameron Diaz",
							ReleaseDate = new DateTime(2001,1,1),
							Duration = 90,
							TicketPrice = 14,
							ImageUrl = @"\images\movie\25039c7b-b056-4c0d-bad7-12ee96428b03.jpg"
						},
						new Movie
						{
							Title = "Terminator",
							Description = "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine," +
							" sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's" +
							" future salvation.",
							Director = "James Cameron",
							MainActor = "Arnold Schwarzenegger, Linda Hamilton, Miachel Biehn",
							ReleaseDate = new DateTime(1984,1,1),
							Duration = 107,
							TicketPrice = 12,
							ImageUrl = @"\images\movie\f08d0ec7-7b23-4391-8b0f-0e304983c980.jpg"
						},
						new Movie
						{
							Title = "Matrix",
							Description = "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking" +
							" truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
							Director = "Lana Wachowski, Lilly Wachowski",
							MainActor = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
							ReleaseDate = new DateTime(1999,1,1),
							Duration = 136,
							TicketPrice = 15, 
							ImageUrl = @"\images\movie\6d170cd5-49e7-4ee1-82b0-2b5d682ca776.jpg"
						},
						new Movie
						{
							Title = "Forrest Gump",
							Description = "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man" +
							" with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
							Director = "Robert Zemeckis",
							MainActor = "Tom Hanks, Robin Wright, Gary Sinise",
							ReleaseDate = new DateTime(1994,1,1),
							Duration = 144,
							TicketPrice = 13,
							ImageUrl = @"\images\movie\376d85b9-57a7-48cd-8c7a-7b7419278ea0.jpg"
						},
						new Movie
						{
							Title = "Pulp Fiction",
							Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in" +
							" four tales of violence and redemption.",
							Director = "Quentin Tarantino",
							MainActor = "John Travolta, Uma Thurman, Samuel L. Jackson",
							ReleaseDate = new DateTime(1994,1,1),
							Duration = 154,
							TicketPrice = 15,
							ImageUrl = @"\images\movie\63004796-770f-45a3-89d3-fad6472dcbba.jpg"
						},
						new Movie
						{
							Title = "Inception",
							Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task" +
							" of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
							Director = "Christopher Nolan",
							MainActor = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
							ReleaseDate = new DateTime(2010,1,1),
							Duration = 148,
							TicketPrice = 14,
							ImageUrl =  @"\images\movie\482579b2-f877-4a28-a88f-87f3be99c252.jpg"
						},
						new Movie
						{
							Title = "Whiplash",
							Description = "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored" +
							" by an instructor who will stop at nothing to realize a student's potential.",
							Director = "Damien Chazelle",
							MainActor = "Miles Teller, J.K. Simmons, Melissa Benoist",
							ReleaseDate = new DateTime(2014,1,1),
							Duration = 106,
							TicketPrice = 12,
							ImageUrl = @"\images\movie\adb86119-783b-43be-a30f-c6c9674c506a.jpg"
						},
						new Movie
						{
							Title = "Apocalypse Now",
							Description = "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees " +
							"himself as a god.",
							Director = "Francis Ford Coppola",
							MainActor = "Martin Sheen, Marlon Brando, Robert Duvall",
							ReleaseDate = new DateTime(1979,1,1),
							Duration = 147,
							TicketPrice = 13,
							ImageUrl = @"\images\movie\d02de66a-a883-4116-818b-93c247e43e66.jpg"
						},
					});
					db.SaveChanges();
				}

				if (!db.MovieGenres.Any())
				{
					db.MovieGenres.AddRange(new List<MovieGenre>
					{
						new MovieGenre { MovieId = 1, GenreId = 1 },
						new MovieGenre { MovieId = 1, GenreId = 8 },
						new MovieGenre { MovieId = 2, GenreId = 4 },
						new MovieGenre { MovieId = 2, GenreId = 6 },
						new MovieGenre { MovieId = 3, GenreId = 4 },
						new MovieGenre { MovieId = 3, GenreId = 6 },
						new MovieGenre { MovieId = 4, GenreId = 5 },
						new MovieGenre { MovieId = 4, GenreId = 9 },
						new MovieGenre { MovieId = 4, GenreId = 3 },
						new MovieGenre { MovieId = 5, GenreId = 5 },
						new MovieGenre { MovieId = 5, GenreId = 7 },
						new MovieGenre { MovieId = 6, GenreId = 4 },
						new MovieGenre { MovieId = 6, GenreId = 6 },
						new MovieGenre { MovieId = 7, GenreId = 5 },
						new MovieGenre { MovieId = 7, GenreId = 10 },
						new MovieGenre { MovieId = 8, GenreId = 5 },
						new MovieGenre { MovieId = 8, GenreId = 9 }
					});
					db.SaveChanges();
				}

				if (!db.Rooms.Any())
				{
					db.Rooms.AddRange(new List<Room>
					{
						new Room { Number = 1 },
						new Room { Number = 2 },
						new Room { Number = 3 },
						new Room { Number = 4 }
					});
					db.SaveChanges();
				}

				if (!db.Screenings.Any())
				{
					db.Screenings.AddRange(new List<Screening>
					{
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(9).AddMinutes(15), RoomId = 1},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(11).AddMinutes(0), RoomId = 1},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(12).AddMinutes(45), RoomId = 1},
						new Screening { MovieId = 4, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(14).AddMinutes(30), RoomId = 1},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(17).AddMinutes(15), RoomId = 1},
						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(20).AddMinutes(0), RoomId = 1},
						new Screening { MovieId = 2, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(22).AddMinutes(00), RoomId = 1},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(9).AddMinutes(15), RoomId = 1},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(11).AddMinutes(0), RoomId = 1},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(12).AddMinutes(45), RoomId = 1},
						new Screening { MovieId = 4, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(14).AddMinutes(30), RoomId = 1},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(17).AddMinutes(15), RoomId = 1},
						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(20).AddMinutes(0), RoomId = 1},
						new Screening { MovieId = 2, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(22).AddMinutes(00), RoomId = 1},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(9).AddMinutes(15), RoomId = 2},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(11).AddMinutes(0), RoomId = 2},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(12).AddMinutes(45), RoomId = 2},
						new Screening { MovieId = 3, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(15).AddMinutes(40), RoomId = 2},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(18).AddMinutes(15), RoomId = 2},
						new Screening { MovieId = 8, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(21).AddMinutes(0), RoomId = 2},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(9).AddMinutes(15), RoomId = 2},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(11).AddMinutes(0), RoomId = 2},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(12).AddMinutes(45), RoomId = 2},
						new Screening { MovieId = 3, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(15).AddMinutes(40), RoomId = 2},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(18).AddMinutes(15), RoomId = 2},
						new Screening { MovieId = 8, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(21).AddMinutes(0), RoomId = 2},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(9).AddMinutes(15), RoomId = 3},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(11).AddMinutes(0), RoomId = 3},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(12).AddMinutes(45), RoomId = 3},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(1).AddHours(15).AddMinutes(30), RoomId = 3},
						new Screening { MovieId = 6, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(18).AddMinutes(15), RoomId = 3},
						new Screening { MovieId = 8, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(21).AddMinutes(0), RoomId = 3},

						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(9).AddMinutes(15), RoomId = 3},
						new Screening { MovieId = 1, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(11).AddMinutes(0), RoomId = 3},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(12).AddMinutes(45), RoomId = 3},
						new Screening { MovieId = 6, Is3D = true, StartTime = DateTime.Today.AddDays(2).AddHours(15).AddMinutes(30), RoomId = 3},
						new Screening { MovieId = 6, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(18).AddMinutes(15), RoomId = 3},
						new Screening { MovieId = 8, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(21).AddMinutes(0), RoomId = 3},

						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(9).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(11).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(13).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 4, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(16).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(19).AddMinutes(0), RoomId = 4},
						new Screening { MovieId = 2, Is3D = false, StartTime = DateTime.Today.AddDays(1).AddHours(22).AddMinutes(0), RoomId = 4},

						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(9).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 7, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(11).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(13).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 4, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(16).AddMinutes(15), RoomId = 4},
						new Screening { MovieId = 5, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(19).AddMinutes(0), RoomId = 4},
						new Screening { MovieId = 2, Is3D = false, StartTime = DateTime.Today.AddDays(2).AddHours(22).AddMinutes(0), RoomId = 4},
					});
					db.SaveChanges();
				}

				if (!db.Seats.Any())
				{
					db.Seats.AddRange(new List<Seat>
					{
						new Seat { Row = 1, Number = 1, RoomId = 1 },
						new Seat { Row = 1, Number = 2, RoomId = 1 },
						new Seat { Row = 1, Number = 3, RoomId = 1 },
						new Seat { Row = 1, Number = 4, RoomId = 1 },
						new Seat { Row = 1, Number = 5, RoomId = 1 },
						new Seat { Row = 1, Number = 6, RoomId = 1 },
						new Seat { Row = 1, Number = 7, RoomId = 1 },
						new Seat { Row = 1, Number = 8, RoomId = 1 },
						new Seat { Row = 1, Number = 9, RoomId = 1 },
						new Seat { Row = 1, Number = 10, RoomId = 1 },
						new Seat { Row = 1, Number = 11, RoomId = 1 },
						new Seat { Row = 1, Number = 12, RoomId = 1 },
						new Seat { Row = 1, Number = 13, RoomId = 1 },
						new Seat { Row = 1, Number = 14, RoomId = 1 },
						new Seat { Row = 1, Number = 15, RoomId = 1 },
						new Seat { Row = 1, Number = 16, RoomId = 1 },
						new Seat { Row = 2, Number = 1, RoomId = 1 },
						new Seat { Row = 2, Number = 2, RoomId = 1 },
						new Seat { Row = 2, Number = 3, RoomId = 1 },
						new Seat { Row = 2, Number = 4, RoomId = 1 },
						new Seat { Row = 2, Number = 5, RoomId = 1 },
						new Seat { Row = 2, Number = 6, RoomId = 1 },
						new Seat { Row = 2, Number = 7, RoomId = 1 },
						new Seat { Row = 2, Number = 8, RoomId = 1 },
						new Seat { Row = 2, Number = 9, RoomId = 1 },
						new Seat { Row = 2, Number = 10, RoomId = 1 },
						new Seat { Row = 2, Number = 11, RoomId = 1 },
						new Seat { Row = 2, Number = 12, RoomId = 1 },
						new Seat { Row = 2, Number = 13, RoomId = 1 },
						new Seat { Row = 2, Number = 14, RoomId = 1 },
						new Seat { Row = 2, Number = 15, RoomId = 1 },
						new Seat { Row = 2, Number = 16, RoomId = 1 },
						new Seat { Row = 3, Number = 1, RoomId = 1 },
						new Seat { Row = 3, Number = 2, RoomId = 1 },
						new Seat { Row = 3, Number = 3, RoomId = 1 },
						new Seat { Row = 3, Number = 4, RoomId = 1 },
						new Seat { Row = 3, Number = 5, RoomId = 1 },
						new Seat { Row = 3, Number = 6, RoomId = 1 },
						new Seat { Row = 3, Number = 7, RoomId = 1 },
						new Seat { Row = 3, Number = 8, RoomId = 1 },
						new Seat { Row = 3, Number = 9, RoomId = 1 },
						new Seat { Row = 3, Number = 10, RoomId = 1 },
						new Seat { Row = 3, Number = 11, RoomId = 1 },
						new Seat { Row = 3, Number = 12, RoomId = 1 },
						new Seat { Row = 3, Number = 13, RoomId = 1 },
						new Seat { Row = 3, Number = 14, RoomId = 1 },
						new Seat { Row = 3, Number = 15, RoomId = 1 },
						new Seat { Row = 3, Number = 16, RoomId = 1 },
						new Seat { Row = 4, Number = 1, RoomId = 1 },
						new Seat { Row = 4, Number = 2, RoomId = 1 },
						new Seat { Row = 4, Number = 3, RoomId = 1 },
						new Seat { Row = 4, Number = 4, RoomId = 1 },
						new Seat { Row = 4, Number = 5, RoomId = 1 },
						new Seat { Row = 4, Number = 6, RoomId = 1 },
						new Seat { Row = 4, Number = 7, RoomId = 1 },
						new Seat { Row = 4, Number = 8, RoomId = 1 },
						new Seat { Row = 4, Number = 9, RoomId = 1 },
						new Seat { Row = 4, Number = 10, RoomId = 1 },
						new Seat { Row = 4, Number = 11, RoomId = 1 },
						new Seat { Row = 4, Number = 12, RoomId = 1 },
						new Seat { Row = 4, Number = 13, RoomId = 1 },
						new Seat { Row = 4, Number = 14, RoomId = 1 },
						new Seat { Row = 4, Number = 15, RoomId = 1 },
						new Seat { Row = 4, Number = 16, RoomId = 1 },
						new Seat { Row = 5, Number = 1, RoomId = 1 },
						new Seat { Row = 5, Number = 2, RoomId = 1 },
						new Seat { Row = 5, Number = 3, RoomId = 1 },
						new Seat { Row = 5, Number = 4, RoomId = 1 },
						new Seat { Row = 5, Number = 5, RoomId = 1 },
						new Seat { Row = 5, Number = 6, RoomId = 1 },
						new Seat { Row = 5, Number = 7, RoomId = 1 },
						new Seat { Row = 5, Number = 8, RoomId = 1 },
						new Seat { Row = 5, Number = 9, RoomId = 1 },
						new Seat { Row = 5, Number = 10, RoomId = 1 },
						new Seat { Row = 5, Number = 11, RoomId = 1 },
						new Seat { Row = 5, Number = 12, RoomId = 1 },
						new Seat { Row = 5, Number = 13, RoomId = 1 },
						new Seat { Row = 5, Number = 14, RoomId = 1 },
						new Seat { Row = 5, Number = 15, RoomId = 1 },
						new Seat { Row = 5, Number = 16, RoomId = 1 },
						new Seat { Row = 6, Number = 1, RoomId = 1 },
						new Seat { Row = 6, Number = 2, RoomId = 1 },
						new Seat { Row = 6, Number = 3, RoomId = 1 },
						new Seat { Row = 6, Number = 4, RoomId = 1 },
						new Seat { Row = 6, Number = 5, RoomId = 1 },
						new Seat { Row = 6, Number = 6, RoomId = 1 },
						new Seat { Row = 6, Number = 7, RoomId = 1 },
						new Seat { Row = 6, Number = 8, RoomId = 1 },
						new Seat { Row = 6, Number = 9, RoomId = 1 },
						new Seat { Row = 6, Number = 10, RoomId = 1 },
						new Seat { Row = 6, Number = 11, RoomId = 1 },
						new Seat { Row = 6, Number = 12, RoomId = 1 },
						new Seat { Row = 6, Number = 13, RoomId = 1 },
						new Seat { Row = 6, Number = 14, RoomId = 1 },
						new Seat { Row = 6, Number = 15, RoomId = 1 },
						new Seat { Row = 6, Number = 16, RoomId = 1 },
						new Seat { Row = 7, Number = 1, RoomId = 1 },
						new Seat { Row = 7, Number = 2, RoomId = 1 },
						new Seat { Row = 7, Number = 3, RoomId = 1 },
						new Seat { Row = 7, Number = 4, RoomId = 1 },
						new Seat { Row = 7, Number = 5, RoomId = 1 },
						new Seat { Row = 7, Number = 6, RoomId = 1 },
						new Seat { Row = 7, Number = 7, RoomId = 1 },
						new Seat { Row = 7, Number = 8, RoomId = 1 },
						new Seat { Row = 7, Number = 9, RoomId = 1 },
						new Seat { Row = 7, Number = 10, RoomId = 1 },
						new Seat { Row = 7, Number = 11, RoomId = 1 },
						new Seat { Row = 7, Number = 12, RoomId = 1 },
						new Seat { Row = 7, Number = 13, RoomId = 1 },
						new Seat { Row = 7, Number = 14, RoomId = 1 },
						new Seat { Row = 7, Number = 15, RoomId = 1 },
						new Seat { Row = 7, Number = 16, RoomId = 1 },
						new Seat { Row = 8, Number = 1, RoomId = 1 },
						new Seat { Row = 8, Number = 2, RoomId = 1 },
						new Seat { Row = 8, Number = 3, RoomId = 1 },
						new Seat { Row = 8, Number = 4, RoomId = 1 },
						new Seat { Row = 8, Number = 5, RoomId = 1 },
						new Seat { Row = 8, Number = 6, RoomId = 1 },
						new Seat { Row = 8, Number = 7, RoomId = 1 },
						new Seat { Row = 8, Number = 8, RoomId = 1 },
						new Seat { Row = 8, Number = 9, RoomId = 1 },
						new Seat { Row = 8, Number = 10, RoomId = 1 },
						new Seat { Row = 8, Number = 11, RoomId = 1 },
						new Seat { Row = 8, Number = 12, RoomId = 1 },
						new Seat { Row = 8, Number = 13, RoomId = 1 },
						new Seat { Row = 8, Number = 14, RoomId = 1 },
						new Seat { Row = 8, Number = 15, RoomId = 1 },
						new Seat { Row = 8, Number = 16, RoomId = 1 },
						new Seat { Row = 9, Number = 1, RoomId = 1 },
						new Seat { Row = 9, Number = 2, RoomId = 1 },
						new Seat { Row = 9, Number = 3, RoomId = 1 },
						new Seat { Row = 9, Number = 4, RoomId = 1 },
						new Seat { Row = 9, Number = 5, RoomId = 1 },
						new Seat { Row = 9, Number = 6, RoomId = 1 },
						new Seat { Row = 9, Number = 7, RoomId = 1 },
						new Seat { Row = 9, Number = 8, RoomId = 1 },
						new Seat { Row = 9, Number = 9, RoomId = 1 },
						new Seat { Row = 9, Number = 10, RoomId = 1 },
						new Seat { Row = 9, Number = 11, RoomId = 1 },
						new Seat { Row = 9, Number = 12, RoomId = 1 },
						new Seat { Row = 9, Number = 13, RoomId = 1 },
						new Seat { Row = 9, Number = 14, RoomId = 1 },
						new Seat { Row = 9, Number = 15, RoomId = 1 },
						new Seat { Row = 9, Number = 16, RoomId = 1 },
						new Seat { Row = 10, Number = 1, RoomId = 1 },
						new Seat { Row = 10, Number = 2, RoomId = 1 },
						new Seat { Row = 10, Number = 3, RoomId = 1 },
						new Seat { Row = 10, Number = 4, RoomId = 1 },
						new Seat { Row = 10, Number = 5, RoomId = 1 },
						new Seat { Row = 10, Number = 6, RoomId = 1 },
						new Seat { Row = 10, Number = 7, RoomId = 1 },
						new Seat { Row = 10, Number = 8, RoomId = 1 },
						new Seat { Row = 10, Number = 9, RoomId = 1 },
						new Seat { Row = 10, Number = 10, RoomId = 1 },
						new Seat { Row = 10, Number = 11, RoomId = 1 },
						new Seat { Row = 10, Number = 12, RoomId = 1 },
						new Seat { Row = 10, Number = 13, RoomId = 1 },
						new Seat { Row = 10, Number = 14, RoomId = 1 },
						new Seat { Row = 10, Number = 15, RoomId = 1 },
						new Seat { Row = 10, Number = 16, RoomId = 1 },

						new Seat { Row = 1, Number = 1, RoomId = 2 },
						new Seat { Row = 1, Number = 2, RoomId = 2 },
						new Seat { Row = 1, Number = 3, RoomId = 2 },
						new Seat { Row = 1, Number = 4, RoomId = 2 },
						new Seat { Row = 1, Number = 5, RoomId = 2 },
						new Seat { Row = 1, Number = 6, RoomId = 2 },
						new Seat { Row = 1, Number = 7, RoomId = 2 },
						new Seat { Row = 1, Number = 8, RoomId = 2 },
						new Seat { Row = 1, Number = 9, RoomId = 2 },
						new Seat { Row = 1, Number = 10, RoomId = 2 },
						new Seat { Row = 1, Number = 11, RoomId = 2 },
						new Seat { Row = 1, Number = 12, RoomId = 2 },
						new Seat { Row = 1, Number = 13, RoomId = 2 },
						new Seat { Row = 1, Number = 14, RoomId = 2 },
						new Seat { Row = 1, Number = 15, RoomId = 2 },
						new Seat { Row = 1, Number = 16, RoomId = 2 },
						new Seat { Row = 2, Number = 1, RoomId = 2 },
						new Seat { Row = 2, Number = 2, RoomId = 2 },
						new Seat { Row = 2, Number = 3, RoomId = 2 },
						new Seat { Row = 2, Number = 4, RoomId = 2 },
						new Seat { Row = 2, Number = 5, RoomId = 2 },
						new Seat { Row = 2, Number = 6, RoomId = 2 },
						new Seat { Row = 2, Number = 7, RoomId = 2 },
						new Seat { Row = 2, Number = 8, RoomId = 2 },
						new Seat { Row = 2, Number = 9, RoomId = 2 },
						new Seat { Row = 2, Number = 10, RoomId = 2 },
						new Seat { Row = 2, Number = 11, RoomId = 2 },
						new Seat { Row = 2, Number = 12, RoomId = 2 },
						new Seat { Row = 2, Number = 13, RoomId = 2 },
						new Seat { Row = 2, Number = 14, RoomId = 2 },
						new Seat { Row = 2, Number = 15, RoomId = 2 },
						new Seat { Row = 2, Number = 16, RoomId = 2 },
						new Seat { Row = 3, Number = 1, RoomId = 2 },
						new Seat { Row = 3, Number = 2, RoomId = 2 },
						new Seat { Row = 3, Number = 3, RoomId = 2 },
						new Seat { Row = 3, Number = 4, RoomId = 2 },
						new Seat { Row = 3, Number = 5, RoomId = 2 },
						new Seat { Row = 3, Number = 6, RoomId = 2 },
						new Seat { Row = 3, Number = 7, RoomId = 2 },
						new Seat { Row = 3, Number = 8, RoomId = 2 },
						new Seat { Row = 3, Number = 9, RoomId = 2 },
						new Seat { Row = 3, Number = 10, RoomId = 2 },
						new Seat { Row = 3, Number = 11, RoomId = 2 },
						new Seat { Row = 3, Number = 12, RoomId = 2 },
						new Seat { Row = 3, Number = 13, RoomId = 2 },
						new Seat { Row = 3, Number = 14, RoomId = 2 },
						new Seat { Row = 3, Number = 15, RoomId = 2 },
						new Seat { Row = 3, Number = 16, RoomId = 2 },
						new Seat { Row = 4, Number = 1, RoomId = 2 },
						new Seat { Row = 4, Number = 2, RoomId = 2 },
						new Seat { Row = 4, Number = 3, RoomId = 2 },
						new Seat { Row = 4, Number = 4, RoomId = 2 },
						new Seat { Row = 4, Number = 5, RoomId = 2 },
						new Seat { Row = 4, Number = 6, RoomId = 2 },
						new Seat { Row = 4, Number = 7, RoomId = 2 },
						new Seat { Row = 4, Number = 8, RoomId = 2 },
						new Seat { Row = 4, Number = 9, RoomId = 2 },
						new Seat { Row = 4, Number = 10, RoomId = 2 },
						new Seat { Row = 4, Number = 11, RoomId = 2 },
						new Seat { Row = 4, Number = 12, RoomId = 2 },
						new Seat { Row = 4, Number = 13, RoomId = 2 },
						new Seat { Row = 4, Number = 14, RoomId = 2 },
						new Seat { Row = 4, Number = 15, RoomId = 2 },
						new Seat { Row = 4, Number = 16, RoomId = 2 },
						new Seat { Row = 5, Number = 1, RoomId = 2 },
						new Seat { Row = 5, Number = 2, RoomId = 2 },
						new Seat { Row = 5, Number = 3, RoomId = 2 },
						new Seat { Row = 5, Number = 4, RoomId = 2 },
						new Seat { Row = 5, Number = 5, RoomId = 2 },
						new Seat { Row = 5, Number = 6, RoomId = 2 },
						new Seat { Row = 5, Number = 7, RoomId = 2 },
						new Seat { Row = 5, Number = 8, RoomId = 2 },
						new Seat { Row = 5, Number = 9, RoomId = 2 },
						new Seat { Row = 5, Number = 10, RoomId = 2 },
						new Seat { Row = 5, Number = 11, RoomId = 2 },
						new Seat { Row = 5, Number = 12, RoomId = 2 },
						new Seat { Row = 5, Number = 13, RoomId = 2 },
						new Seat { Row = 5, Number = 14, RoomId = 2 },
						new Seat { Row = 5, Number = 15, RoomId = 2 },
						new Seat { Row = 5, Number = 16, RoomId = 2 },
						new Seat { Row = 6, Number = 1, RoomId = 2 },
						new Seat { Row = 6, Number = 2, RoomId = 2 },
						new Seat { Row = 6, Number = 3, RoomId = 2 },
						new Seat { Row = 6, Number = 4, RoomId = 2 },
						new Seat { Row = 6, Number = 5, RoomId = 2 },
						new Seat { Row = 6, Number = 6, RoomId = 2 },
						new Seat { Row = 6, Number = 7, RoomId = 2 },
						new Seat { Row = 6, Number = 8, RoomId = 2 },
						new Seat { Row = 6, Number = 9, RoomId = 2 },
						new Seat { Row = 6, Number = 10, RoomId = 2 },
						new Seat { Row = 6, Number = 11, RoomId = 2 },
						new Seat { Row = 6, Number = 12, RoomId = 2 },
						new Seat { Row = 6, Number = 13, RoomId = 2 },
						new Seat { Row = 6, Number = 14, RoomId = 2 },
						new Seat { Row = 6, Number = 15, RoomId = 2 },
						new Seat { Row = 6, Number = 16, RoomId = 2 },
						new Seat { Row = 7, Number = 1, RoomId = 2 },
						new Seat { Row = 7, Number = 2, RoomId = 2 },
						new Seat { Row = 7, Number = 3, RoomId = 2 },
						new Seat { Row = 7, Number = 4, RoomId = 2 },
						new Seat { Row = 7, Number = 5, RoomId = 2 },
						new Seat { Row = 7, Number = 6, RoomId = 2 },
						new Seat { Row = 7, Number = 7, RoomId = 2 },
						new Seat { Row = 7, Number = 8, RoomId = 2 },
						new Seat { Row = 7, Number = 9, RoomId = 2 },
						new Seat { Row = 7, Number = 10, RoomId = 2 },
						new Seat { Row = 7, Number = 11, RoomId = 2 },
						new Seat { Row = 7, Number = 12, RoomId = 2 },
						new Seat { Row = 7, Number = 13, RoomId = 2 },
						new Seat { Row = 7, Number = 14, RoomId = 2 },
						new Seat { Row = 7, Number = 15, RoomId = 2 },
						new Seat { Row = 7, Number = 16, RoomId = 2 },
						new Seat { Row = 8, Number = 1, RoomId = 2 },
						new Seat { Row = 8, Number = 2, RoomId = 2 },
						new Seat { Row = 8, Number = 3, RoomId = 2 },
						new Seat { Row = 8, Number = 4, RoomId = 2 },
						new Seat { Row = 8, Number = 5, RoomId = 2 },
						new Seat { Row = 8, Number = 6, RoomId = 2 },
						new Seat { Row = 8, Number = 7, RoomId = 2 },
						new Seat { Row = 8, Number = 8, RoomId = 2 },
						new Seat { Row = 8, Number = 9, RoomId = 2 },
						new Seat { Row = 8, Number = 10, RoomId = 2 },
						new Seat { Row = 8, Number = 11, RoomId = 2 },
						new Seat { Row = 8, Number = 12, RoomId = 2 },
						new Seat { Row = 8, Number = 13, RoomId = 2 },
						new Seat { Row = 8, Number = 14, RoomId = 2 },
						new Seat { Row = 8, Number = 15, RoomId = 2 },
						new Seat { Row = 8, Number = 16, RoomId = 2 },
						new Seat { Row = 9, Number = 1, RoomId = 2 },
						new Seat { Row = 9, Number = 2, RoomId = 2 },
						new Seat { Row = 9, Number = 3, RoomId = 2 },
						new Seat { Row = 9, Number = 4, RoomId = 2 },
						new Seat { Row = 9, Number = 5, RoomId = 2 },
						new Seat { Row = 9, Number = 6, RoomId = 2 },
						new Seat { Row = 9, Number = 7, RoomId = 2 },
						new Seat { Row = 9, Number = 8, RoomId = 2 },
						new Seat { Row = 9, Number = 9, RoomId = 2 },
						new Seat { Row = 9, Number = 10, RoomId = 2 },
						new Seat { Row = 9, Number = 11, RoomId = 2 },
						new Seat { Row = 9, Number = 12, RoomId = 2 },
						new Seat { Row = 9, Number = 13, RoomId = 2 },
						new Seat { Row = 9, Number = 14, RoomId = 2 },
						new Seat { Row = 9, Number = 15, RoomId = 2 },
						new Seat { Row = 9, Number = 16, RoomId = 2 },
						new Seat { Row = 10, Number = 1, RoomId = 2 },
						new Seat { Row = 10, Number = 2, RoomId = 2 },
						new Seat { Row = 10, Number = 3, RoomId = 2 },
						new Seat { Row = 10, Number = 4, RoomId = 2 },
						new Seat { Row = 10, Number = 5, RoomId = 2 },
						new Seat { Row = 10, Number = 6, RoomId = 2 },
						new Seat { Row = 10, Number = 7, RoomId = 2 },
						new Seat { Row = 10, Number = 8, RoomId = 2 },
						new Seat { Row = 10, Number = 9, RoomId = 2 },
						new Seat { Row = 10, Number = 10, RoomId = 2 },
						new Seat { Row = 10, Number = 11, RoomId = 2 },
						new Seat { Row = 10, Number = 12, RoomId = 2 },
						new Seat { Row = 10, Number = 13, RoomId = 2 },
						new Seat { Row = 10, Number = 14, RoomId = 2 },
						new Seat { Row = 10, Number = 15, RoomId = 2 },
						new Seat { Row = 10, Number = 16, RoomId = 2 },

						new Seat { Row = 1, Number = 1, RoomId = 3 },
						new Seat { Row = 1, Number = 2, RoomId = 3 },
						new Seat { Row = 1, Number = 3, RoomId = 3 },
						new Seat { Row = 1, Number = 4, RoomId = 3 },
						new Seat { Row = 1, Number = 5, RoomId = 3 },
						new Seat { Row = 1, Number = 6, RoomId = 3 },
						new Seat { Row = 1, Number = 7, RoomId = 3 },
						new Seat { Row = 1, Number = 8, RoomId = 3 },
						new Seat { Row = 1, Number = 9, RoomId = 3 },
						new Seat { Row = 1, Number = 10, RoomId = 3 },
						new Seat { Row = 1, Number = 11, RoomId = 3 },
						new Seat { Row = 1, Number = 12, RoomId = 3 },
						new Seat { Row = 1, Number = 13, RoomId = 3 },
						new Seat { Row = 1, Number = 14, RoomId = 3 },
						new Seat { Row = 1, Number = 15, RoomId = 3 },
						new Seat { Row = 1, Number = 16, RoomId = 3 },
						new Seat { Row = 2, Number = 1, RoomId = 3 },
						new Seat { Row = 2, Number = 2, RoomId = 3 },
						new Seat { Row = 2, Number = 3, RoomId = 3 },
						new Seat { Row = 2, Number = 4, RoomId = 3 },
						new Seat { Row = 2, Number = 5, RoomId = 3 },
						new Seat { Row = 2, Number = 6, RoomId = 3 },
						new Seat { Row = 2, Number = 7, RoomId = 3 },
						new Seat { Row = 2, Number = 8, RoomId = 3 },
						new Seat { Row = 2, Number = 9, RoomId = 3 },
						new Seat { Row = 2, Number = 10, RoomId = 3 },
						new Seat { Row = 2, Number = 11, RoomId = 3 },
						new Seat { Row = 2, Number = 12, RoomId = 3 },
						new Seat { Row = 2, Number = 13, RoomId = 3 },
						new Seat { Row = 2, Number = 14, RoomId = 3 },
						new Seat { Row = 2, Number = 15, RoomId = 3 },
						new Seat { Row = 2, Number = 16, RoomId = 3 },
						new Seat { Row = 3, Number = 1, RoomId = 3 },
						new Seat { Row = 3, Number = 2, RoomId = 3 },
						new Seat { Row = 3, Number = 3, RoomId = 3 },
						new Seat { Row = 3, Number = 4, RoomId = 3 },
						new Seat { Row = 3, Number = 5, RoomId = 3 },
						new Seat { Row = 3, Number = 6, RoomId = 3 },
						new Seat { Row = 3, Number = 7, RoomId = 3 },
						new Seat { Row = 3, Number = 8, RoomId = 3 },
						new Seat { Row = 3, Number = 9, RoomId = 3 },
						new Seat { Row = 3, Number = 10, RoomId = 3 },
						new Seat { Row = 3, Number = 11, RoomId = 3 },
						new Seat { Row = 3, Number = 12, RoomId = 3 },
						new Seat { Row = 3, Number = 13, RoomId = 3 },
						new Seat { Row = 3, Number = 14, RoomId = 3 },
						new Seat { Row = 3, Number = 15, RoomId = 3 },
						new Seat { Row = 3, Number = 16, RoomId = 3 },
						new Seat { Row = 4, Number = 1, RoomId = 3 },
						new Seat { Row = 4, Number = 2, RoomId = 3 },
						new Seat { Row = 4, Number = 3, RoomId = 3 },
						new Seat { Row = 4, Number = 4, RoomId = 3 },
						new Seat { Row = 4, Number = 5, RoomId = 3 },
						new Seat { Row = 4, Number = 6, RoomId = 3 },
						new Seat { Row = 4, Number = 7, RoomId = 3 },
						new Seat { Row = 4, Number = 8, RoomId = 3 },
						new Seat { Row = 4, Number = 9, RoomId = 3 },
						new Seat { Row = 4, Number = 10, RoomId = 3 },
						new Seat { Row = 4, Number = 11, RoomId = 3 },
						new Seat { Row = 4, Number = 12, RoomId = 3 },
						new Seat { Row = 4, Number = 13, RoomId = 3 },
						new Seat { Row = 4, Number = 14, RoomId = 3 },
						new Seat { Row = 4, Number = 15, RoomId = 3 },
						new Seat { Row = 4, Number = 16, RoomId = 3 },
						new Seat { Row = 5, Number = 1, RoomId = 3 },
						new Seat { Row = 5, Number = 2, RoomId = 3 },
						new Seat { Row = 5, Number = 3, RoomId = 3 },
						new Seat { Row = 5, Number = 4, RoomId = 3 },
						new Seat { Row = 5, Number = 5, RoomId = 3 },
						new Seat { Row = 5, Number = 6, RoomId = 3 },
						new Seat { Row = 5, Number = 7, RoomId = 3 },
						new Seat { Row = 5, Number = 8, RoomId = 3 },
						new Seat { Row = 5, Number = 9, RoomId = 3 },
						new Seat { Row = 5, Number = 10, RoomId = 3 },
						new Seat { Row = 5, Number = 11, RoomId = 3 },
						new Seat { Row = 5, Number = 12, RoomId = 3 },
						new Seat { Row = 5, Number = 13, RoomId = 3 },
						new Seat { Row = 5, Number = 14, RoomId = 3 },
						new Seat { Row = 5, Number = 15, RoomId = 3 },
						new Seat { Row = 5, Number = 16, RoomId = 3 },
						new Seat { Row = 6, Number = 1, RoomId = 3 },
						new Seat { Row = 6, Number = 2, RoomId = 3 },
						new Seat { Row = 6, Number = 3, RoomId = 3 },
						new Seat { Row = 6, Number = 4, RoomId = 3 },
						new Seat { Row = 6, Number = 5, RoomId = 3 },
						new Seat { Row = 6, Number = 6, RoomId = 3 },
						new Seat { Row = 6, Number = 7, RoomId = 3 },
						new Seat { Row = 6, Number = 8, RoomId = 3 },
						new Seat { Row = 6, Number = 9, RoomId = 3 },
						new Seat { Row = 6, Number = 10, RoomId = 3 },
						new Seat { Row = 6, Number = 11, RoomId = 3 },
						new Seat { Row = 6, Number = 12, RoomId = 3 },
						new Seat { Row = 6, Number = 13, RoomId = 3 },
						new Seat { Row = 6, Number = 14, RoomId = 3 },
						new Seat { Row = 6, Number = 15, RoomId = 3 },
						new Seat { Row = 6, Number = 16, RoomId = 3 },
						new Seat { Row = 7, Number = 1, RoomId = 3 },
						new Seat { Row = 7, Number = 2, RoomId = 3 },
						new Seat { Row = 7, Number = 3, RoomId = 3 },
						new Seat { Row = 7, Number = 4, RoomId = 3 },
						new Seat { Row = 7, Number = 5, RoomId = 3 },
						new Seat { Row = 7, Number = 6, RoomId = 3 },
						new Seat { Row = 7, Number = 7, RoomId = 3 },
						new Seat { Row = 7, Number = 8, RoomId = 3 },
						new Seat { Row = 7, Number = 9, RoomId = 3 },
						new Seat { Row = 7, Number = 10, RoomId = 3 },
						new Seat { Row = 7, Number = 11, RoomId = 3 },
						new Seat { Row = 7, Number = 12, RoomId = 3 },
						new Seat { Row = 7, Number = 13, RoomId = 3 },
						new Seat { Row = 7, Number = 14, RoomId = 3 },
						new Seat { Row = 7, Number = 15, RoomId = 3 },
						new Seat { Row = 7, Number = 16, RoomId = 3 },
						new Seat { Row = 8, Number = 1, RoomId = 3 },
						new Seat { Row = 8, Number = 2, RoomId = 3 },
						new Seat { Row = 8, Number = 3, RoomId = 3 },
						new Seat { Row = 8, Number = 4, RoomId = 3 },
						new Seat { Row = 8, Number = 5, RoomId = 3 },
						new Seat { Row = 8, Number = 6, RoomId = 3 },
						new Seat { Row = 8, Number = 7, RoomId = 3 },
						new Seat { Row = 8, Number = 8, RoomId = 3 },
						new Seat { Row = 8, Number = 9, RoomId = 3 },
						new Seat { Row = 8, Number = 10, RoomId = 3 },
						new Seat { Row = 8, Number = 11, RoomId = 3 },
						new Seat { Row = 8, Number = 12, RoomId = 3 },
						new Seat { Row = 8, Number = 13, RoomId = 3 },
						new Seat { Row = 8, Number = 14, RoomId = 3 },
						new Seat { Row = 8, Number = 15, RoomId = 3 },
						new Seat { Row = 8, Number = 16, RoomId = 3 },
						new Seat { Row = 9, Number = 1, RoomId = 3 },
						new Seat { Row = 9, Number = 2, RoomId = 3 },
						new Seat { Row = 9, Number = 3, RoomId = 3 },
						new Seat { Row = 9, Number = 4, RoomId = 3 },
						new Seat { Row = 9, Number = 5, RoomId = 3 },
						new Seat { Row = 9, Number = 6, RoomId = 3 },
						new Seat { Row = 9, Number = 7, RoomId = 3 },
						new Seat { Row = 9, Number = 8, RoomId = 3 },
						new Seat { Row = 9, Number = 9, RoomId = 3 },
						new Seat { Row = 9, Number = 10, RoomId = 3 },
						new Seat { Row = 9, Number = 11, RoomId = 3 },
						new Seat { Row = 9, Number = 12, RoomId = 3 },
						new Seat { Row = 9, Number = 13, RoomId = 3 },
						new Seat { Row = 9, Number = 14, RoomId = 3 },
						new Seat { Row = 9, Number = 15, RoomId = 3 },
						new Seat { Row = 9, Number = 16, RoomId = 3 },
						new Seat { Row = 10, Number = 1, RoomId = 3 },
						new Seat { Row = 10, Number = 2, RoomId = 3 },
						new Seat { Row = 10, Number = 3, RoomId = 3 },
						new Seat { Row = 10, Number = 4, RoomId = 3 },
						new Seat { Row = 10, Number = 5, RoomId = 3 },
						new Seat { Row = 10, Number = 6, RoomId = 3 },
						new Seat { Row = 10, Number = 7, RoomId = 3 },
						new Seat { Row = 10, Number = 8, RoomId = 3 },
						new Seat { Row = 10, Number = 9, RoomId = 3 },
						new Seat { Row = 10, Number = 10, RoomId = 3 },
						new Seat { Row = 10, Number = 11, RoomId = 3 },
						new Seat { Row = 10, Number = 12, RoomId = 3 },
						new Seat { Row = 10, Number = 13, RoomId = 3 },
						new Seat { Row = 10, Number = 14, RoomId = 3 },
						new Seat { Row = 10, Number = 15, RoomId = 3 },
						new Seat { Row = 10, Number = 16, RoomId = 3 },

						new Seat { Row = 1, Number = 1, RoomId = 4 },
						new Seat { Row = 1, Number = 2, RoomId = 4 },
						new Seat { Row = 1, Number = 3, RoomId = 4 },
						new Seat { Row = 1, Number = 4, RoomId = 4 },
						new Seat { Row = 1, Number = 5, RoomId = 4 },
						new Seat { Row = 1, Number = 6, RoomId = 4 },
						new Seat { Row = 1, Number = 7, RoomId = 4 },
						new Seat { Row = 1, Number = 8, RoomId = 4 },
						new Seat { Row = 1, Number = 9, RoomId = 4 },
						new Seat { Row = 1, Number = 10, RoomId = 4 },
						new Seat { Row = 1, Number = 11, RoomId = 4 },
						new Seat { Row = 1, Number = 12, RoomId = 4 },
						new Seat { Row = 1, Number = 13, RoomId = 4 },
						new Seat { Row = 1, Number = 14, RoomId = 4 },
						new Seat { Row = 1, Number = 15, RoomId = 4 },
						new Seat { Row = 1, Number = 16, RoomId = 4 },
						new Seat { Row = 2, Number = 1, RoomId = 4 },
						new Seat { Row = 2, Number = 2, RoomId = 4 },
						new Seat { Row = 2, Number = 3, RoomId = 4 },
						new Seat { Row = 2, Number = 4, RoomId = 4 },
						new Seat { Row = 2, Number = 5, RoomId = 4 },
						new Seat { Row = 2, Number = 6, RoomId = 4 },
						new Seat { Row = 2, Number = 7, RoomId = 4 },
						new Seat { Row = 2, Number = 8, RoomId = 4 },
						new Seat { Row = 2, Number = 9, RoomId = 4 },
						new Seat { Row = 2, Number = 10, RoomId = 4 },
						new Seat { Row = 2, Number = 11, RoomId = 4 },
						new Seat { Row = 2, Number = 12, RoomId = 4 },
						new Seat { Row = 2, Number = 13, RoomId = 4 },
						new Seat { Row = 2, Number = 14, RoomId = 4 },
						new Seat { Row = 2, Number = 15, RoomId = 4 },
						new Seat { Row = 2, Number = 16, RoomId = 4 },
						new Seat { Row = 3, Number = 1, RoomId = 4 },
						new Seat { Row = 3, Number = 2, RoomId = 4 },
						new Seat { Row = 3, Number = 3, RoomId = 4 },
						new Seat { Row = 3, Number = 4, RoomId = 4 },
						new Seat { Row = 3, Number = 5, RoomId = 4 },
						new Seat { Row = 3, Number = 6, RoomId = 4 },
						new Seat { Row = 3, Number = 7, RoomId = 4 },
						new Seat { Row = 3, Number = 8, RoomId = 4 },
						new Seat { Row = 3, Number = 9, RoomId = 4 },
						new Seat { Row = 3, Number = 10, RoomId = 4 },
						new Seat { Row = 3, Number = 11, RoomId = 4 },
						new Seat { Row = 3, Number = 12, RoomId = 4 },
						new Seat { Row = 3, Number = 13, RoomId = 4 },
						new Seat { Row = 3, Number = 14, RoomId = 4 },
						new Seat { Row = 3, Number = 15, RoomId = 4 },
						new Seat { Row = 3, Number = 16, RoomId = 4 },
						new Seat { Row = 4, Number = 1, RoomId = 4 },
						new Seat { Row = 4, Number = 2, RoomId = 4 },
						new Seat { Row = 4, Number = 3, RoomId = 4 },
						new Seat { Row = 4, Number = 4, RoomId = 4 },
						new Seat { Row = 4, Number = 5, RoomId = 4 },
						new Seat { Row = 4, Number = 6, RoomId = 4 },
						new Seat { Row = 4, Number = 7, RoomId = 4 },
						new Seat { Row = 4, Number = 8, RoomId = 4 },
						new Seat { Row = 4, Number = 9, RoomId = 4 },
						new Seat { Row = 4, Number = 10, RoomId = 4 },
						new Seat { Row = 4, Number = 11, RoomId = 4 },
						new Seat { Row = 4, Number = 12, RoomId = 4 },
						new Seat { Row = 4, Number = 13, RoomId = 4 },
						new Seat { Row = 4, Number = 14, RoomId = 4 },
						new Seat { Row = 4, Number = 15, RoomId = 4 },
						new Seat { Row = 4, Number = 16, RoomId = 4 },
						new Seat { Row = 5, Number = 1, RoomId = 4 },
						new Seat { Row = 5, Number = 2, RoomId = 4 },
						new Seat { Row = 5, Number = 3, RoomId = 4 },
						new Seat { Row = 5, Number = 4, RoomId = 4 },
						new Seat { Row = 5, Number = 5, RoomId = 4 },
						new Seat { Row = 5, Number = 6, RoomId = 4 },
						new Seat { Row = 5, Number = 7, RoomId = 4 },
						new Seat { Row = 5, Number = 8, RoomId = 4 },
						new Seat { Row = 5, Number = 9, RoomId = 4 },
						new Seat { Row = 5, Number = 10, RoomId = 4 },
						new Seat { Row = 5, Number = 11, RoomId = 4 },
						new Seat { Row = 5, Number = 12, RoomId = 4 },
						new Seat { Row = 5, Number = 13, RoomId = 4 },
						new Seat { Row = 5, Number = 14, RoomId = 4 },
						new Seat { Row = 5, Number = 15, RoomId = 4 },
						new Seat { Row = 5, Number = 16, RoomId = 4 },
						new Seat { Row = 6, Number = 1, RoomId = 4 },
						new Seat { Row = 6, Number = 2, RoomId = 4 },
						new Seat { Row = 6, Number = 3, RoomId = 4 },
						new Seat { Row = 6, Number = 4, RoomId = 4 },
						new Seat { Row = 6, Number = 5, RoomId = 4 },
						new Seat { Row = 6, Number = 6, RoomId = 4 },
						new Seat { Row = 6, Number = 7, RoomId = 4 },
						new Seat { Row = 6, Number = 8, RoomId = 4 },
						new Seat { Row = 6, Number = 9, RoomId = 4 },
						new Seat { Row = 6, Number = 10, RoomId = 4 },
						new Seat { Row = 6, Number = 11, RoomId = 4 },
						new Seat { Row = 6, Number = 12, RoomId = 4 },
						new Seat { Row = 6, Number = 13, RoomId = 4 },
						new Seat { Row = 6, Number = 14, RoomId = 4 },
						new Seat { Row = 6, Number = 15, RoomId = 4 },
						new Seat { Row = 6, Number = 16, RoomId = 4 },
						new Seat { Row = 7, Number = 1, RoomId = 4 },
						new Seat { Row = 7, Number = 2, RoomId = 4 },
						new Seat { Row = 7, Number = 3, RoomId = 4 },
						new Seat { Row = 7, Number = 4, RoomId = 4 },
						new Seat { Row = 7, Number = 5, RoomId = 4 },
						new Seat { Row = 7, Number = 6, RoomId = 4 },
						new Seat { Row = 7, Number = 7, RoomId = 4 },
						new Seat { Row = 7, Number = 8, RoomId = 4 },
						new Seat { Row = 7, Number = 9, RoomId = 4 },
						new Seat { Row = 7, Number = 10, RoomId = 4 },
						new Seat { Row = 7, Number = 11, RoomId = 4 },
						new Seat { Row = 7, Number = 12, RoomId = 4 },
						new Seat { Row = 7, Number = 13, RoomId = 4 },
						new Seat { Row = 7, Number = 14, RoomId = 4 },
						new Seat { Row = 7, Number = 15, RoomId = 4 },
						new Seat { Row = 7, Number = 16, RoomId = 4 },
						new Seat { Row = 8, Number = 1, RoomId = 4 },
						new Seat { Row = 8, Number = 2, RoomId = 4 },
						new Seat { Row = 8, Number = 3, RoomId = 4 },
						new Seat { Row = 8, Number = 4, RoomId = 4 },
						new Seat { Row = 8, Number = 5, RoomId = 4 },
						new Seat { Row = 8, Number = 6, RoomId = 4 },
						new Seat { Row = 8, Number = 7, RoomId = 4 },
						new Seat { Row = 8, Number = 8, RoomId = 4 },
						new Seat { Row = 8, Number = 9, RoomId = 4 },
						new Seat { Row = 8, Number = 10, RoomId = 4 },
						new Seat { Row = 8, Number = 11, RoomId = 4 },
						new Seat { Row = 8, Number = 12, RoomId = 4 },
						new Seat { Row = 8, Number = 13, RoomId = 4 },
						new Seat { Row = 8, Number = 14, RoomId = 4 },
						new Seat { Row = 8, Number = 15, RoomId = 4 },
						new Seat { Row = 8, Number = 16, RoomId = 4 },
						new Seat { Row = 9, Number = 1, RoomId = 4 },
						new Seat { Row = 9, Number = 2, RoomId = 4 },
						new Seat { Row = 9, Number = 3, RoomId = 4 },
						new Seat { Row = 9, Number = 4, RoomId = 4 },
						new Seat { Row = 9, Number = 5, RoomId = 4 },
						new Seat { Row = 9, Number = 6, RoomId = 4 },
						new Seat { Row = 9, Number = 7, RoomId = 4 },
						new Seat { Row = 9, Number = 8, RoomId = 4 },
						new Seat { Row = 9, Number = 9, RoomId = 4 },
						new Seat { Row = 9, Number = 10, RoomId = 4 },
						new Seat { Row = 9, Number = 11, RoomId = 4 },
						new Seat { Row = 9, Number = 12, RoomId = 4 },
						new Seat { Row = 9, Number = 13, RoomId = 4 },
						new Seat { Row = 9, Number = 14, RoomId = 4 },
						new Seat { Row = 9, Number = 15, RoomId = 4 },
						new Seat { Row = 9, Number = 16, RoomId = 4 },
						new Seat { Row = 10, Number = 1, RoomId = 4 },
						new Seat { Row = 10, Number = 2, RoomId = 4 },
						new Seat { Row = 10, Number = 3, RoomId = 4 },
						new Seat { Row = 10, Number = 4, RoomId = 4 },
						new Seat { Row = 10, Number = 5, RoomId = 4 },
						new Seat { Row = 10, Number = 6, RoomId = 4 },
						new Seat { Row = 10, Number = 7, RoomId = 4 },
						new Seat { Row = 10, Number = 8, RoomId = 4 },
						new Seat { Row = 10, Number = 9, RoomId = 4 },
						new Seat { Row = 10, Number = 10, RoomId = 4 },
						new Seat { Row = 10, Number = 11, RoomId = 4 },
						new Seat { Row = 10, Number = 12, RoomId = 4 },
						new Seat { Row = 10, Number = 13, RoomId = 4 },
						new Seat { Row = 10, Number = 14, RoomId = 4 },
						new Seat { Row = 10, Number = 15, RoomId = 4 },
						new Seat { Row = 10, Number = 16, RoomId = 4 }
					});
					db.SaveChanges();
				}
			}
		}
	}
}
